poseidon/matchbox

Documentation/physical-hardware.md, Documentation/troubleshooting.md, Documentation/virtual-hardware.md, README.md, examples/README.md, examples/kubernetes/README.md, examples/kubernetes/cloud/etcd.yaml, examples/kubernetes/cloud/master.sh, examples/kubernetes/cloud/worker.sh, examples/kubernetes/config.yaml, examples/kubernetes/ignition/etcd.json, examples/kubernetes/ignition/master.json, examples/kubernetes/ignition/worker.json, examples/kubernetes/kubeconfig, examples/kubernetes/scripts/generate-tls, examples/kubernetes/scripts/kubernetes-cert, examples/kubernetes/scripts/root-ca, examples/kubernetes/specs/etcd/spec.json, examples/kubernetes/specs/master/spec.json, examples/kubernetes/specs/worker/spec.json
* Add TLS asset generation based on coreos-kubernetes
* Add kubernetes example cluster (1 master, 1 worker, 1 etcd)
=> Add Kubernetes cluster example

Documentation/getting-started-docker.md, Documentation/getting-started-rkt.md, api/cloud.go, api/groups.go, api/groups_test.go, api/ignition.go, examples/etcd-rkt.yaml, examples/ignition/coreos-install.yaml, examples/ignition/etcd.yaml, examples/ignition/etcd_proxy.yaml, examples/ignition/network.yaml, examples/k8s-rkt.yaml
* Support templating lists into Ignition (e.g. SSH authorized keys)
* Closes #47
=> api: Allow nested map[string]interface{} template data

Documentation/api.md, Documentation/bootcfg.md, Documentation/config.md, Documentation/getting-started-docker.md, Documentation/getting-started-rkt.md, Documentation/network-booting.md, Documentation/physical-hardware.md, Documentation/virtual-hardware.md, README.md, contrib/dnsmasq/README.md, examples/README.md
* Add docs for new features, simplify presentation
* Use the name bootcfg when referring to the service
=> docs: Update docs with new features

examples/README.md, examples/coreos-install.yaml, examples/ignition/format-disk.yaml, examples/pxe-disk.yaml, examples/pxe.yaml, examples/specs/pxe-disk/spec.json, examples/specs/pxe/spec.json, scripts/libvirt
* Resolves #72, needed for #71
=> examples: Partition disk, root fs, and PXE with root fs

scripts/get-coreos
=> scripts: Improve message for incorrect CoreOS channel/version

Documentation/dev/release.md, Documentation/getting-started-rkt.md
=> docs: Show rkt trust, fetch, and run of signed ACI

Documentation/dev/develop.md, examples/ignition/format-disk.yaml
=> examples: Correct wipeTable to wipe_table in YAML

bootcfg/config/config.go, bootcfg/config/config_test.go
=> config: Normalize MAC addresses from group requirements YAML

CHANGES.md, Documentation/bootcfg.md, Documentation/config.md, Documentation/dev/develop.md, Documentation/getting-started-docker.md, Documentation/getting-started-rkt.md, Documentation/openpgp.md, README.md, cmd/bootcfg-rpc/main.go, cmd/bootcfg/main.go, examples/README.md
* Change default -config path to /etc/bootcfg.conf
* Change default -data-path to /etc/bootcfg
* Change default -assets-path to /var/bootcfg
=> cmd, docs: Change default config, data, and assets locations

Documentation/deployment.md, Makefile, README.md, contrib/systemd/bootcfg.service, examples/default.yaml
Resolves #80. Don't merge until "specs" are renamed to "profiles" #49.
=> Add build and systemd deploy example

CHANGES.md, Documentation/getting-started-docker.md, Documentation/getting-started-rkt.md, examples/README.md, examples/groups/k8s-docker/node1.json, examples/groups/k8s-docker/node2.json, examples/groups/k8s-docker/node3.json, examples/groups/k8s-install/node1.json, examples/groups/k8s-install/node2.json, examples/groups/k8s-install/node3.json, examples/groups/k8s/node1.json, examples/groups/k8s/node2.json, examples/groups/k8s/node3.json, examples/ignition/k8s-master.yaml, examples/ignition/k8s-worker.yaml
=> Start Heapster by default in k8s examples

CHANGES.md, Documentation/bootcfg.md, bootcfg/http/server.go, cmd/bootcfg/main.go
* Pass -assets-path="" to disable asset serving. Defaults to
/var/lib/bootcfg/assets.
* Resolves #118
=> Allow disabling asset serving

Documentation/deployment.md, Makefile, README.md, contrib/k8s/bootcfg-deployment.yaml, contrib/k8s/bootcfg-service.yaml
=> docs: Add rkt, Docker, and Kubernetes bootcfg deployment notes

CHANGES.md, Documentation/kubernetes.md, examples/README.md, examples/ignition/k8s-master.yaml, examples/ignition/k8s-worker.yaml
* Add some missing changelog entries as well
=> examples/profiles/k8s: Update k8s cluster to v1.2.3

bootcfg/storage/storagepb/group.go, bootcfg/storage/storagepb/group_test.go, bootcfg/storage/storagepb/profile.go, bootcfg/storage/storagepb/profile_test.go
=> bootcfg/storage: Add Copy methods to Profile and Group

examples/ignition/bootkube-master.yaml, examples/ignition/bootkube-worker.yaml, examples/ignition/etcd.yaml, examples/ignition/k8s-master.yaml, examples/ignition/k8s-worker.yaml
* Don't allow etcd clusters to reconfigure themselves to lose quorum
=> examples/etcd: Enable etcd strict reconfig check

CHANGES.md, Documentation/kubernetes.md, examples/README.md, examples/ignition/k8s-master.yaml, examples/ignition/k8s-worker.yaml, scripts/tls/kubernetes-cert
* Add missing kubernetes.default.svc alt name to openssl config
cc @aaronlevy @chancez
=> examples/k8s: Update k8s to v1.2.4 and openssl conf

Documentation/deployment.md, Makefile, contrib/systemd/bootcfg.service, scripts/setup-data-dir
* Setup /var/lib/bootcfg with the bootcfg group
Deployment opinions from @colhom or @cgag?
=> contrib/systemd: Run bootcfg with bootcfg user and group

Documentation/config.md, Makefile
=> Improve documentation of bootcfg arguments and files

CHANGES.md, bootcfg/http/server.go
=> bootcfg/http/server: Log requests for bootcfg assets

CHANGES.md, Documentation/bootkube.md, Documentation/kubernetes.md, Documentation/torus.md, README.md, examples/README.md, examples/groups/torus/node1.json, examples/groups/torus/node2.json, examples/groups/torus/node3.json, examples/ignition/torus.yaml, examples/profiles/torus.json
=> examples: Add Torus cluster example and tutorial

scripts/rkt-gc-force
the previous script was not working for me with rkt 1.8.0
=> scripts: update rkt-gc-force for rkt 1.8.0

.gitignore, Makefile, scripts/release-files
=> Makefile: Add release tarball target

examples/ignition/k8s-master.yaml
=> examples/ignition: Add -xe to bash scripts

examples/ignition/install-reboot.yaml, examples/ignition/install-shutdown.yaml
* Does nothing to address #250
@dm0- @crawford
=> examples/ignition: Separate installer.service script

bootcfg/client/client.go, bootcfg/client/doc.go
=> bootcfg/client: Accept a gRPC DialTimeout option

scripts/get-coreos
=> scripts: Don't set GPG trust level of CoreOS public key

Documentation/deployment.md, README.md, contrib/k8s/bootcfg-deployment.yaml
=> Documentation: Update installation guide for v0.4.0

Documentation/deployment.md, README.md, contrib/systemd/bootcfg-on-coreos.service, contrib/systemd/bootcfg.service
* Provide a systemd service unit which rkt runs bootcfg
rel. #269 
cc. @sym3tri
=> Documentation: Add guide for installing on CoreOS

CHANGES.md, Documentation/getting-started-rkt.md, examples/etc/bootcfg/cert-gen
=> Usability improvements to tls scripts and docs

README.md, examples/README.md, examples/groups/etcd3/default.json, examples/groups/etcd3/node1.json, examples/groups/etcd3/node2.json, examples/groups/etcd3/node3.json, examples/ignition/etcd3-proxy.yaml, examples/ignition/etcd3.yaml, examples/profiles/etcd3-proxy.json, examples/profiles/etcd3.json
Add etcd3 static DNS reference cluster for bare metal.
@gyuho you guys still want `LimitNOFILE=40000` and other considerations?
rel: https://github.com/coreos/etcd/issues/6177
Closes #314
=> Add etcd3 example cluster with rkt

Documentation/torus.md, examples/README.md, examples/ignition/torus.yaml
* Run Torus' etcd3 with rkt
cc @barakmich 
closes #325
=> examples: Run Torus' etcd3 with rkt

examples/ignition/bootkube-controller.yaml, examples/ignition/etcd.yaml, examples/ignition/etcd3.yaml, examples/ignition/k8s-master.yaml, examples/ignition/rktnetes-controller.yaml, examples/ignition/torus.yaml
* See github.com/coreos/etcd/pull/6365
cc @gyuho
=> examples/ignition: Fix etcd peer listen urls to use IPs

examples/profiles/k8s-controller-install.json, examples/profiles/k8s-controller.json
Examples are looking for k8s-master.yaml file. Also needed to change the profile ids for proper matching.
=> Finished renaming Master -> controller

contrib/dnsmasq/README.md
Highly minor issue, but better to take more time from anyone else, I guess
=> [doc] Fix sample Docker command

scripts/devnet
=> scripts/devnet: Fix devnet to start named examples

Documentation/bootkube-upgrades.md, Documentation/bootkube.md, README.md
I've upgraded several clusters to v1.4.3 and documented that process here.
cc @aaronlevy @sym3tri
=> Documentation: Show self-hosted Kubernetes upgrade process

examples/ignition/bootkube-controller.yaml, examples/ignition/bootkube-worker.yaml, examples/ignition/k8s-controller.yaml, examples/ignition/k8s-worker.yaml, examples/ignition/rktnetes-controller.yaml, examples/ignition/rktnetes-worker.yaml
* Kubelet is reported to crash if cadvisor can't watch
=> examples: Increase the inotify max_user_watches

Documentation/deployment.md, contrib/systemd/bootcfg-for-tectonic.service, contrib/systemd/bootcfg-local.service
=> Documentation: Add RPM install docs

CHANGES.md, Documentation/kubernetes.md, examples/ignition/k8s-controller.yaml, examples/ignition/k8s-worker.yaml
rel: https://github.com/coreos/coreos-kubernetes/pull/769
cc @aaronlevy @pbx0
=> Update Kubernetes (static) to v1.5.1

.travis.yml, CHANGES.md, matchbox/cli/group_create.go, matchbox/cli/group_describe.go, matchbox/cli/group_list.go, matchbox/cli/ignition_create.go, matchbox/cli/profile_create.go, matchbox/cli/profile_describe.go, matchbox/cli/profile_list.go, matchbox/http/cloud.go, matchbox/http/cloud_test.go, matchbox/http/context.go, matchbox/http/context_test.go, matchbox/http/ctxh.go, matchbox/http/ctxh_test.go, matchbox/http/generic.go, matchbox/http/generic_test.go, matchbox/http/grub.go, matchbox/http/handlers.go, matchbox/http/handlers_test.go, matchbox/http/ignition.go, matchbox/http/ignition_test.go, matchbox/http/ipxe.go, matchbox/http/ipxe_test.go, matchbox/http/metadata.go, matchbox/http/metadata_test.go, matchbox/http/pixiecore.go, matchbox/http/pixiecore_test.go, matchbox/server/server.go, matchbox/server/server_test.go
* Drop build support for Go 1.6
=> matchbox: Switch to Go 1.7+ standard context

CHANGES.md, Documentation/bootkube.md, Documentation/kubernetes.md, Documentation/rktnetes.md, examples/groups/bootkube-install/node1.json, examples/groups/bootkube-install/node2.json, examples/groups/bootkube-install/node3.json, examples/groups/bootkube/node1.json, examples/groups/bootkube/node2.json, examples/groups/bootkube/node3.json, examples/ignition/bootkube-controller.yaml, examples/ignition/bootkube-worker.yaml, examples/ignition/k8s-controller.yaml, examples/ignition/k8s-worker.yaml
This self-hosted configuration is already in use in Tectonic v1.5.2 and also in https://github.com/dghubble/metal
=> Update example Kubernetes clusters to v1.5.2

Documentation/getting-started-docker.md
Remove unnecessary "$" prefixes
=> Docs: fix entries in the /etc/hosts section

Documentation/deployment.md
ref https://github.com/coreos-inc/tectonic/pull/1451
=> Doc/deployment: s/general/generic linux distros

CHANGES.md, Documentation/bootkube.md, examples/ignition/bootkube-controller.yaml, scripts/get-bootkube
* Builds on #447 to test this bump in a somewhat automated-way
* https://jenkins-tectonic.prod.coreos.systems/job/matchbox/ 37
cc @pbx0
=> Update self-hosted Kubernetes to v1.5.3 and use bootkube v0.3.9

contrib/dnsmasq/docker0.conf, contrib/dnsmasq/metal0.conf
=> contrib/dnsmasq: Add a 4th node for multi-k8s tests

Documentation/matchbox.md
There appears to be a comma missing in the code sample.
=> Add missing comma

examples/terraform/.gitignore, examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/bootkube.tf, examples/terraform/bootkube-install/provider.tf, examples/terraform/bootkube-install/variables.tf, examples/terraform/etcd3-install/etcd3.tf, examples/terraform/etcd3-install/provider.tf, examples/terraform/etcd3-install/variables.tf, examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl, examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl, examples/terraform/modules/profiles/cl/coreos-install.yaml.tmpl, examples/terraform/modules/profiles/cl/etcd3-gateway.yaml.tmpl, examples/terraform/modules/profiles/cl/etcd3.yaml.tmpl, examples/terraform/modules/profiles/outputs.tf, examples/terraform/modules/profiles/profiles.tf, examples/terraform/modules/profiles/variables.tf
Moving from https://github.com/coreos/terraform-provider-matchbox/tree/master/examples
=> Add terraform examples for etcd3 and self-hosted Kubernetes

CHANGES.md, Documentation/deployment.md, Documentation/matchbox.md, README.md, examples/README.md
* Fix a few reamining CoreOS -> Container Linux cases
=> CHANGE.md: Update changelog with notable recent changes

Documentation/matchbox.md, README.md
* Updates matchbox description cc @philips 
* Links to coreos docs and structures the README to be similar to those docs cc @ElijahCaine
=> README: Update README structure and description

Documentation/getting-started-rkt.md, Documentation/grub.md, Documentation/network-setup.md, contrib/dnsmasq/README.md
=> Documentation: Add back original rkt run dnsmasq --caps-retain

contrib/rpm/matchbox.spec
=> contrib/rpm: Bump to re-build RPM release now Copr is fixed

Documentation/deployment.md, Documentation/proxy-setup.md, contrib/squid/README.md
Tracking items to move from draft to docs in #511.
=> Add squid proxy docs as contrib drafts

Documentation/deployment.md
=> Documentation: Add missing mkdir for rkt/docker installation

Documentation/api.md, Documentation/bootkube.md, Documentation/deployment.md, Documentation/getting-started-docker.md, Documentation/getting-started-rkt.md, Documentation/matchbox.md, contrib/dnsmasq/get-tftp-files, examples/README.md, examples/groups/bootkube-install/install.json, examples/groups/etcd3-install/install.json, examples/groups/simple-install/install.json, examples/profiles/bootkube-controller.json, examples/profiles/bootkube-worker.json, examples/profiles/etcd3-gateway.json, examples/profiles/etcd3.json, examples/profiles/grub.json, examples/profiles/install-reboot.json, examples/profiles/simple-install.json, examples/profiles/simple.json, examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/terraform.tfvars.example, examples/terraform/etcd3-install/etcd3.tf, scripts/devnet, scripts/get-coreos, tests/smoke/bootkube.tfvars
Rebases #540 and runs cluster tests. Minor fixes.
=> Bump Container Linux version to stable 1353.7.0

examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/multi-controller.tfvars.example
=> examples/terraform: Add tfvars showing multi-controller case

Documentation/deployment.md, Documentation/dev/release.md, Documentation/getting-started-rkt.md, README.md, contrib/k8s/matchbox-deployment.yaml, contrib/systemd/matchbox-for-tectonic.service, contrib/systemd/matchbox-on-coreos.service
=> *: Update docs references to v0.6.1

Jenkinsfile
Use the newer, declarative pipeline style.
Related to #486, but does not close.
=> Jenkinsfile: Switch to declarative-style Jenkins pipeline

Documentation/api.md, Documentation/cloud-config.md, README.md, matchbox/http/cloud.go
* Warn that Cloud-Config support will be removed in the future
Closes #563
=> matchbox,Documentation: Mark Cloud-Config as deprecated

Jenkinsfile, tests/smoke/bootkube-terraform
* Simplify script to not launch subshells
* Verify tests don't leave behind processes running terraform apply
Closes #508
=> Re-enable bootkube-terraform cluster tests

examples/ignition/bootkube-controller.yaml, examples/ignition/etcd3-gateway.yaml, examples/ignition/etcd3.yaml, examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl, examples/terraform/modules/profiles/cl/etcd3-gateway.yaml.tmpl, examples/terraform/modules/profiles/cl/etcd3.yaml.tmpl
https://github.com/coreos/etcd/releases/tag/v3.2.0
=> examples: Update etcd3 from v3.1.6 to v3.2.0

Documentation/bootkube-upgrades.md
I've verified these docs doing an in-place update of a bare-metal cluster. Notable changes:
* Daemonsets support rolling upgrades so just edit and wait!
* Kubelet is no longer run as a pod so editing the env file on each host is required
* Added new section calling about how Tectonic users should NOT follow this
cc @kbrwn @andrewwebber
Closes #612
=> Documentation: Refresh Kubernetes in-place upgrade doc

examples/addons/cluo/update-agent.yaml, examples/addons/cluo/update-operator.yaml
See https://github.com/coreos/container-linux-update-operator/pull/120
=> examples/addonts: Update CLUO from v0.2.1 to v0.2.2

Documentation/bootkube-upgrades.md, examples/terraform/modules/bootkube/bootkube.tf
I moved my personal module over to another repo.
=> *: Fix location of the bootkube-terraform module

Documentation/bootkube-upgrades.md, examples/addons/cluo/update-agent.yaml, examples/addons/cluo/update-operator.yaml, examples/terraform/modules/bootkube/bootkube.tf
* Update CLUO addon example from v0.2.2 to v0.3.1
* Update location of bootkube-terraform module
=> Update CLUO version and bootkube-terraform location

Documentation/deployment.md, Documentation/network-setup.md
- Updated coreos versions
- Added code for copying certificates for later use to ~/.matchbox/
- Updated matchbox example host within docker run command
=> Documentation: minor documentation changes

examples/groups/bootkube-install/install.json, examples/groups/etcd3-install/install.json, examples/groups/simple-install/install.json, examples/profiles/bootkube-controller.json, examples/profiles/bootkube-worker.json, examples/profiles/etcd3-gateway.json, examples/profiles/etcd3.json, examples/profiles/grub.json, examples/profiles/install-reboot.json, examples/profiles/simple-install.json, examples/profiles/simple.json
* Bug introduced by b10c777729c9d6174100c935a344e8dc856555ad
=> examples: Fix endpoint name for manual examples

CHANGES.md, Documentation/bootkube.md, README.md, examples/README.md, examples/ignition/bootkube-controller.yaml, examples/ignition/bootkube-worker.yaml, examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/cluster.tf, scripts/dev/get-bootkube
https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.9.0
=> examples: Update from Kubernetes v1.8.3 to v1.8.4

examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/cluster.tf, examples/terraform/bootkube-install/provider.tf
* Explicitly pass provider modules to satisfy constraints
* https://github.com/hashicorp/terraform/issues/16824
=> examples: Fix examples to work with Terraform v0.11.x

CHANGES.md, Documentation/bootkube.md, README.md, contrib/k8s/matchbox-ingress.yaml, examples/README.md, examples/ignition/bootkube-controller.yaml, examples/ignition/bootkube-worker.yaml, examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/cluster.tf, scripts/dev/get-bootkube
https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.9.1
=> Update Kubernetes from v1.8.4 to v1.8.5

Documentation/api.md, Documentation/bootkube.md, Documentation/deployment.md, Documentation/getting-started-docker.md, Documentation/getting-started-rkt.md, Documentation/matchbox.md, examples/README.md, examples/groups/bootkube-install/install.json, examples/groups/etcd3-install/install.json, examples/groups/simple-install/install.json, examples/profiles/bootkube-controller.json, examples/profiles/bootkube-worker.json, examples/profiles/etcd3-gateway.json, examples/profiles/etcd3.json, examples/profiles/grub.json, examples/profiles/install-reboot.json, examples/profiles/simple-install.json, examples/profiles/simple.json, examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/multi-controller.tfvars.example, examples/terraform/bootkube-install/terraform.tfvars.example, examples/terraform/etcd3-install/etcd3.tf, scripts/devnet, scripts/get-coreos, tests/smoke/bootkube.tfvars
https://coreos.com/releases/#1576.5.0
=> Bump Container Linux version from 1576.4.0 to 1576.5.0

scripts/dev/git-version, scripts/dev/release-files, scripts/dev/test, scripts/dev/travis-docker-push, scripts/devnet, scripts/get-coreos, scripts/libvirt, scripts/tls/cert-gen
=> scripts: fix shebangs.

examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/cluster.tf
=> examples: Update terraform Kubernetes examples to v1.9.3

README.md, examples/README.md, examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/cluster.tf, examples/terraform/bootkube-install/multi-controller.tfvars.example, examples/terraform/bootkube-install/terraform.tfvars.example, examples/terraform/bootkube-install/variables.tf
* https://github.com/poseidon/typhoon/releases/tag/v1.10.3
```
$ kubectl get nodes
NAME                STATUS    ROLES               AGE       VERSION
node1.example.com   Ready     controller,master   5m        v1.10.3
node2.example.com   Ready     node                5m        v1.10.3
node3.example.com   Ready     node                5m        v1.10.3
```
=> Update Kubernetes (terraform) example to v1.10.3

Documentation/container-linux-config.md
=> [docs] Typo fix

Documentation/deployment.md, cmd/matchbox/main.go
Add HTTPS support for the non grpc web server. Adds new flags to specify certificates for the webserver
=> HTTPS support for web server

CHANGES.md, Dockerfile
* Modernize the maintainer label format
=> Update base container image from alpine:3.6 to alpine:3.9

README.md
Also remove project callouts, they're not really needed
=> Fix README badges and links

CHANGES.md, README.md, examples/README.md, examples/terraform/bootkube-install/README.md, examples/terraform/bootkube-install/cluster.tf, examples/terraform/bootkube-install/provider.tf
* Set terraform-provider-matchbox version to v0.2.3
* Set terraform-provider-ct version to v0.3.1
=> Update Kubernetes cluster example to v1.14.1

scripts/libvirt
* Examples no longer use this QEMU/KVM instance
=> Remove node4 from the local QEMU/KVM setup

Documentation/network-setup.md
As discussed [here](https://forum.ipxe.org/showthread.php?tid=10746)
=> Document uefi chainloading in proxy mode

Makefile
* Inspect why Travis builds may still show a diff
=> Add verbose version output in Makefile

contrib/k8s/matchbox-deployment.yaml, contrib/systemd/matchbox-on-coreos.service, docs/deployment.md, docs/dev/release.md
* Update release versions within the project. Plan to bump every release.
=> Bump outdated release version in docs and examples

scripts/get-fedora-coreos
* Refer to Fedora CoreOS 31 download paths
* https://github.com/poseidon/typhoon/pull/624
=> Update get-fedora-coreos convenience script

mkdocs.yml, requirements.txt
* https://github.com/squidfunk/mkdocs-material/releases/tag/5.2.0
=> Upgrade mkdocs-material from v4.6.2 to v5.2.0

requirements.txt
* Update mkdocs-material from v5.2.0 to v5.2.2
=> Update mkdocs-material from v5.2.0 to v5.2.2

.travis.yml, CHANGES.md
* Remove Go v1.11 test coverage
=> Add Go v1.14 test coverage and CHANGES notes

.github/bug_report.md, .github/config.yml, README.md
* Add standard poisedon bug report template and a link for reporting security issues
=> Add Github issue template for bug reports

CHANGES.md, Dockerfile, contrib/dnsmasq/Dockerfile
* Update base image for matchbox and contrib/dnsmasq
=> Update alpine base image from v3.11 to v3.12

requirements.txt
* Update other docs packages as well
=> Update mkdocs-material from v5.2.2 to v5.3.0

mkdocs.yml, requirements.txt
* Add missing copyright footer info
=> Update mkdocs-material from v5.5.1 to v5.5.12

scripts/libvirt
* https://github.com/coreos/fedora-coreos-docs/pull/196
=> Reset QEM/KVM memory to 2GB for local nodes

.dockerignore, Dockerfile, Makefile
* Go build the Matchbox binary in the container image in a docker.io/golang builder stage rather building the binary separately
=> Use multi-stage Dockerfile for image build

Dockerfile
* https://golang.org/doc/devel/release.html#go1.15
=> Update Go version from v1.14.9 to v1.15.3

docs/getting-started.md, requirements.txt
=> Update terraform-provider-ct from v0.6.1 to v0.7.1

requirements.txt
* Update mkdocs related pypi package dependencies
=> Update docs pypi dependencies

.github/dependabot.yaml
* Check for Go module and Dockerfile updates
* Check for mkdocs PyPi updates (for docs site) weekly
=> Add dependabot Go/docker/PyPi watchers

.github/workflows/test.yaml, go.mod
=> Update Go matrix to add v1.17

.github/deploybot.yaml
* Enable [deploybot.app](https://deploybot.app) to manage production rollouts and auto-deployments of Matchbox to our clusters
Docs: https://docs.deploybot.app/config/
=> Add a deploybot.yaml config file

README.md, scripts/libvirt
* Workaround a bug in virt-install v4.1.0
* Replace Twitter badge with Mastodon badge
Rel: https://github.com/virt-manager/virt-manager/issues/426
=> Add fix to libvirt script and update README badges

.github/dependabot.yaml, .github/workflows/test.yaml, Makefile, go.mod
* Centrally managed Go test workflow across Poseidon repos
=> Change tests to use shared GitHub Workflow from poseidon/.github

CHANGES.md, mkdocs.yml
* Add Ignition docs and remove Container Linux Config docs from the mkdocs navigation and generation
=> Add ignition.md to the mkdocs.yaml navigation

Makefile
* updated the Makefile to also build for Apple M1/M2 platforms.
=> Build for Apple M1/M2 architecture

.github/dependabot.yaml
* Update GitHub Workflows when GitHub Actions when they have new releases
=> Add dependabot to watch GitHub Actions for updates
