poseidon/matchbox

docs/getting-started.md

Old filename was virtual-networking.md, which does not exist.

docs: updated links to virtual-hardware.md

---

Documentation/api.md
Documentation/bootcfg.md
api/machine_test.go
api/pixiecore_test.go
api/spec.go
api/spec_test.go
data/machines/52:54:00:20:17:f9/machine.json
data/machines/default/machine.json
data/specs/orion/spec.json

* If `data/machines/default/machine.json` exists, apply the Spec it
defines or references to all machines not matched by UUID or MAC

api: Allow default machine Spec selector

---

.dockerignore
.gitignore
CHANGES.md
Documentation/api.md
Documentation/bootcfg.md
Documentation/config.md
Documentation/physical-hardware.md
Documentation/virtual-hardware.md
api/server.go
cmd/bootcfg/main.go
examples/dev/specs/default/spec.json
examples/dev/specs/node1/spec.json
examples/dev/specs/node2/spec.json
examples/etcd-large/specs/etcd1/spec.json
examples/etcd-large/specs/etcd2/spec.json
examples/etcd-large/specs/etcd3/spec.json
examples/etcd-large/specs/worker/spec.json
examples/etcd-small/specs/etcd/spec.json
examples/etcd-small/specs/worker/spec.json
scripts/get-coreos
scripts/pixiecore

* Serve assets from /assets, remove /images endpoint
* Migrate images to assets so we have a place for general assets

Rename -images-path to -assets-path

---

Godeps/Godeps.json
Godeps/_workspace/src/golang.org/x/net/context/context.go
Godeps/_workspace/src/golang.org/x/net/context/context_test.go
Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/cancelreq.go
Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/cancelreq_go14.go
Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/ctxhttp.go
Godeps/_workspace/src/golang.org/x/net/context/ctxhttp/ctxhttp_test.go
Godeps/_workspace/src/golang.org/x/net/context/withtimeout_test.go
api/cloud.go
api/cloud_test.go
api/context.go
api/context_test.go
api/groups.go
api/groups_test.go
api/http.go
api/http_test.go
api/ignition.go
api/ignition_test.go
api/ipxe.go
api/ipxe_test.go
api/matchers.go
api/pixiecore.go
api/pixiecore_test.go
api/server.go
api/spec.go
api/spec_test.go

* Vendor golang.org/x/net/context
* Add ContextHandler from github.com/dghubble/ctxh
* Perform machine matching logic in the matchSpecHandler ContextHandler
* Simplify the "leaf" handlers and their tests
* Allocate a single groupsResource at API server creation

Use ContextHandlers to isolate common SpecMatchHandler functionality

---

Dockerfile
build
docker-build

There is no reason to force this. Instead have the docker-build command
do it before it is built.
Also, use the actual package name: bootcfg. It confused me that bootcfg
was called server.

build: don't force GOOS=linux

---

.travis.yml

* Future binaries are expected to make use of Go crypto

travis: Require Go 1.5.3 to run the image deploy

---

Documentation/bootcfg.md

on GitHub it shows up as random icons if you don't put it in backticks
`:cd` shows up like this:  :cd

bootcfg.md:  fix appearance of MAC example

---

examples/etcd-large/cloud/etcd1.yaml
examples/etcd-large/cloud/etcd2.yaml
examples/etcd-large/cloud/etcd3.yaml
examples/etcd-large/ignition/etcd1.json
examples/etcd-large/ignition/etcd2.json
examples/etcd-large/ignition/etcd3.json
examples/etcd-large/specs/etcd1/spec.json
examples/etcd-large/specs/etcd2/spec.json
examples/etcd-large/specs/etcd3/spec.json
examples/etcd-small/cloud/etcd.yaml
examples/etcd-small/ignition/etcd.json
examples/etcd-small/specs/etcd/spec.json

Favor configuring networkd before init rather than adding
networkd units in cloud config, marking the interface down,
and restarting networkd

examples: Configure networkd with Ignition in etcd examples

---

Dockerfile
dockerfiles/dnsmasq/Dockerfile

* Absolute entrypoints are expected for docker2aci

dockerfiles: Fix entrypoints to be absolute paths

---

Documentation/getting-started-rkt.md
examples/README.md
examples/coreos-install.yaml

* Supplied metal0 CNI definition restricted traffic destinations
to the metal0 bridge. Update to allow outbound traffic.
* Fixes the coreos-install example for use with rkt

examples: Fix CNI metal0's destination routes

---

Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
examples/README.md
examples/coreos-install.yaml
examples/ignition/coreos-install.yaml
examples/specs/coreos-install/spec.json

* Use the coreos-install -i option added in CoreOS alpha 949.0.0
* Download second stage Ignition config while in PXE first stage
* Resolves #46

examples: Show CoreOS install with Ignition support

---

.travis.yml
api/http_test.go

* Test request could not be created due to a regression in `url.Parse` https://github.com/golang/go/issues/14573
* Update the example "bad" MAC address. It was a coincidence that the bad MAC ended in "?", using `x:x:x:x:x:x` tests the same handler behavior.

travis: Add Go 1.6 to test matrix, change invalid MAC test

---

Documentation/dev/grub.md
contrib/dnsmasq/README.md

* Bundle grub.efi in coreos/dnsmasq so Docker users can test GRUB netboot with UEFI clients
* Publishing an ACI for rkt in #69 will do the same for rkt users

contrib/dnsmasq: Bundle grub.efi in quay.io/coreos/dnsmasq

---

Documentation/getting-started-rkt.md
examples/coreos-install.yaml
examples/etcd-docker.yaml
examples/etcd-rkt.yaml
examples/ignition/etcd.yaml
examples/ignition/etcd_proxy.yaml
scripts/libvirt

* 4GB disk is too small and routinely fails in libvirt
* Depending on build env, dnsmasq ACI can have an old /etc/resolv.conf
DNS entry embedded. Can rebuild to fix, but use --dns=8.8.8.8 too
* Fix issue where etcd_proxy profile failed to pull metadata
so etcd_proxy wasn't configured after CoreOS install

examples: Fix 2-stage install CoreOS and etcd_proxy setup

---

Documentation/getting-started-rkt.md
contrib/dnsmasq/README.md
contrib/dnsmasq/build-aci

* ACI coreos.com/dnsmasq is available and signed by the CoreOS
Application Signing Key
* Resolves #69

contrib/dnsmasq: Make coreos.com/dnsmasq:v0.2.0 rkt fetch-able

---

examples/README.md
examples/cloud/kubernetes-master.sh
examples/cloud/kubernetes-worker.sh
examples/ignition/network.yaml
examples/k8s-docker.yaml
examples/k8s-rkt.yaml
examples/profiles/kubernetes-master/profile.json
examples/profiles/kubernetes-worker/profile.json

* Upgrade CoreOS Version to Alpha 962.0.0
* rkt run kubelet with the kubelet-wrapper
* Switch to quay.io/coreos/hyperkube
* Provision an ext4 root partition

examples: Upgrade k8s to v1.1.8

---

bootcfg/storage/file_store.go
bootcfg/storage/fs.go
bootcfg/storage/fs_test.go
bootcfg/storage/storage.go

* http.Dir securely restricts accesses to a filesystem directory to
support http FileServe, which is why this type was used originally
* Dir copies the sanatization behavior of http.Dir verbatim, but
provides ioutil-like write and directory access within the directory
* Why: Safe FileStore writes need to be possible and also, storage
should not have a dependency on net/http just for its http.Dir

bootcfg/storage: Switch fileStore from http.Dir to custom Dir

---

examples/groups/etcd-aws/default.json
examples/ignition/etcd-aws.yaml
examples/profiles/etcd-aws.json

* Ignition v2.0.0 could fetch the Ignition config from bootcfg
* Sets up the etcd nodes using the discovery endpoint

examples: Add a POC of how AWS Ignition serving would work

---

CHANGES.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
examples/README.md
examples/groups/k8s-docker/node1.json
examples/groups/k8s-docker/node2.json
examples/groups/k8s-docker/node3.json
examples/groups/k8s-install/node1.json
examples/groups/k8s-install/node2.json
examples/groups/k8s-install/node3.json
examples/groups/k8s/node1.json
examples/groups/k8s/node2.json
examples/groups/k8s/node3.json
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml

Validated both iPXE booted clusters and Installed to Disk clusters using `bootcfg` running via rkt (i.e. `k8s` and `k8s-install` examples). Tested with Tectonic Console and some `Deployments`. Resolves #122 
@pbx0 @aaronlevy

examples: Upgrade k8s from v1.1.8 to v1.2.0

---

bootcfg/http/cloud.go
bootcfg/http/cloud_test.go
bootcfg/http/ignition.go
bootcfg/http/ignition_test.go
bootcfg/http/metadata.go
bootcfg/http/metadata_test.go

* Ignition and Cloud config templates can reference selector key/value pairs by lowercase key name
* Metadata endpoint will provide metadata and selector key/val pairs for the matching machine group
With a group definition like the following, it is possible to reference `{{.uuid}}`, `{{.mac}}`, and {{.networkd_gateway}} in Ignition and Cloud config templates. The three values would also be provided to matching machines at the `/metadata` endpoint.
```
{
"id": "master-node",
"name": "Kubernetes Master",
"profile": "k8s-master",
"selector": {
"uuid": "c307f480-7277-11e3-8720-abcdabcdeadb",
"mac": "52:da:00:89:d8:10"
},
"metadata": {
"networkd_gateway": "192.168.1.1"
}
}
```
Previously, only `{{.networkd_gateway}}` could be used. Resolves #64.

bootcfg/http: Add selectors to template data

---

.dockerignore
.travis.yml
CHANGES.md

Wait a bit for Go 1.6.1 to be released and available.
#139

Upgrade from Go 1.5.3 to Go 1.6.1

---

examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml

* In the k8s-install example, the k8s-certs@.service checks for
the wrong file and always attempts to curl TLS assets from bootcfg.
After restarts or auto-updates, if bootcfg is not running, the certs
are present on disk so the kubelet and k8s cluster operate normally,
while k8s-certs services fail (mostly harmless).
* Fixes k8s-certs@service failures after restarts when bootcfg is
unavailable. Provisioned nodes should not have a hard dependency on
bootcfg service.

examples/ignition: Fix k8s-certs@.service file check

---

examples/groups/k8s-docker/node1.json
examples/groups/k8s-docker/node2.json
examples/groups/k8s-docker/node3.json
examples/groups/k8s-install/node1.json
examples/groups/k8s-install/node2.json
examples/groups/k8s-install/node3.json
examples/groups/k8s/node1.json
examples/groups/k8s/node2.json
examples/groups/k8s/node3.json
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml

* Change Heapster from a rc to a deployment
* Use the heapster-nanny resizer
* Closes #152

examples: Upgrade k8s from v1.2.0 to v1.2.2

---

bootcfg/cli/group_describe.go
bootcfg/cli/profile_describe.go

This PR prevents the following
```sh
$ ./bin/bootcmd --endpoints 172.15.0.2:8081 group describe
ID      NAME    SELECTORS       PROFILE METADATA
panic: runtime error: index out of range
goroutine 1 [running]:
panic(0x8c4680, 0xc82000e120)
/home/joe/.gvm/gos/go1.6.1/src/runtime/panic.go:464 +0x3e6
github.com/coreos/coreos-baremetal/bootcfg/cli.runGroupDescribeCmd(0xc11760, 0xc820195420, 0x0, 0x2)
/home/joe/.gvm/pkgsets/go1.6.1/global/src/github.com/coreos/coreos-baremetal/bootcfg/cli/group_describe.go:32 +0x63c
github.com/coreos/coreos-baremetal/vendor/github.com/spf13/cobra.(*Command).execute(0xc11760, 0xc8201952e0, 0x2, 0x2, 0x0, 0x0)
/home/joe/.gvm/pkgsets/go1.6.1/global/src/github.com/coreos/coreos-baremetal/vendor/github.com/spf13/cobra/command.go:569 +0x85a …
```

bootcmd: fix index-out-of-range on nonsensical describe command

---

Documentation/config.md
bootcfg/http/handlers.go
bootcfg/http/server.go
bootcfg/version/version.go
build
cmd/bootcfg/main.go

* Add `bootcfg/version` package
* Show the `bootcfg` version via the HTTP server at "/" (e.g. `bootcfg version: 7629ac4813781cdf3fe2d3a9f96bc04084b21856`) to supplement the `-version` command line flag.
* Add logging for / rooted tree requests to surface more bad queries
* Fixes incorrect package name in logs #173

Improvements to logging and version display

---

examples/groups/k8s-docker/node2.json
examples/groups/k8s-docker/node3.json
examples/groups/k8s-install/node2.json
examples/groups/k8s-install/node3.json
examples/groups/k8s/node2.json
examples/groups/k8s/node3.json

* k8s worker nodes were provisioned with a typo'd DNS service
IP address (10.3.0.1 instead of 10.3.0.10) which caused DNS to
be misconfigured in pods
* Fixes #180

examples/groups/k8s: Fix DNS resolution in pods

---

bootcfg/http/metadata_test.go
bootcfg/storage/testfakes/fixtures.go
examples/groups/k8s-docker/node1.json
examples/groups/k8s-docker/node2.json
examples/groups/k8s-docker/node3.json
examples/groups/k8s-install/node1.json
examples/groups/k8s-install/node2.json
examples/groups/k8s-install/node3.json
examples/groups/k8s/node1.json
examples/groups/k8s/node2.json
examples/groups/k8s/node3.json
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml

* Setting k8s_version via metadata gives the impression
it can be bumped and the cluster will operate with the
desired version. In reality, the k8s profiles change in
minor but important ways which we validate between k8s
releases. It should be part of the k8s profile Ignition.
* cc @aaronlevy

examples/k8s: Remove k8s_version from machine metadata

---

Documentation/ignition.md
examples/ignition/bootkube-master.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/etcd.yaml
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml

* Profiles should use only the user-provided DNS endpoint.
Adding 8.8.8.8 can cause inconsistent resolution and in some
setups, 8.8.8.8 is not routable.

Remove 8.8.8.8 from networkd example configs

---

Documentation/api.md
Documentation/bootkube.md
Documentation/kubernetes.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/etcd-install/install.json
examples/groups/k8s-install/install.json
examples/profiles/bootkube-master.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd-proxy.json
examples/profiles/etcd.json
examples/profiles/grub.json
examples/profiles/install-reboot.json
examples/profiles/install-shutdown.json
examples/profiles/k8s-master-install.json
examples/profiles/k8s-master.json
examples/profiles/k8s-worker-install.json
examples/profiles/k8s-worker.json
examples/profiles/pxe-disk.json
examples/profiles/pxe.json
scripts/get-coreos
scripts/libvirt

* Default example image should be periodically updated and tested against
* Use an OS version with Ignition 0.4.0 so users aren't confused if they try to use the v2.0.0 format
* I've validated all the example clusters

Update CoreOS version from alpha 983.0.0 to 1032.0.0

---

bootcfg/client/client.go
bootcfg/client/client_test.go
bootcfg/client/doc.go

* Return an error if no endpoints are provided in the client `Config`
* Add a client Close method
* Closes #189

bootcfg/client: Fix New error detection and add Close

---

examples/ignition/ssh.yaml

* Users try to use the latest reference example clusters with
a bootcfg v0.3.0 deployment, which did not yet support Ignition
2.0.0. Wait until closer to v0.4.0 to bump Ignition configs.

example: Revert ssh Ignition config change

---

Documentation/getting-started-rkt.md

The docs had the user skip image verification for an image pulled from
Quay, claiming that since Quay hosts docker images the image is
unsigned. This is true when fetching the docker file with "docker://",
but when an ACI is pulled from Quay (which it converts on the fly), the
ACI will be properly signed.

docs/getting-started-rkt: the --insecure-options flag was unnecessary

---

Documentation/bootkube.md
Documentation/deployment.md
Documentation/kubernetes.md
examples/groups/bootkube-install/node1.json
examples/groups/bootkube-install/node2.json
examples/groups/bootkube-install/node3.json
examples/groups/bootkube/node1.json
examples/groups/bootkube/node2.json
examples/groups/bootkube/node3.json
examples/ignition/bootkube-master.yaml
examples/ignition/bootkube-worker.yaml

* bootkube clusters work with bootkube on-host 5c1efe3ac61e270
* Copy bootkube generated assets and executable to any master
* Change hosts to use kubelet client certificate instead of token
* Update bootkube deployment documentation
* I've tested both the PXE booted and installed to disk bootkube cluster examples
cc @derekparker @aaronlevy

examples/bootkube: Setup bootkube cluster via on-host bootkube

---

CHANGES.md
bootcfg/http/cloud_test.go
bootcfg/http/context.go
bootcfg/http/context_test.go
bootcfg/http/ignition.go
bootcfg/http/ignition_test.go
bootcfg/http/serialize.go
examples/ignition/bootkube-master.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/etcd-aws.yaml
examples/ignition/etcd-proxy.yaml
examples/ignition/etcd.yaml
examples/ignition/format-disk.yaml
examples/ignition/install-reboot.yaml
examples/ignition/install-shutdown.yaml
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml
examples/ignition/ssh.yaml

* Rendering an Ignition config or cloud-config template with machine group metadata will log an error if a metadata value is missing.
* Previously, the default missing value was "no value"
* Closes #190 
@mischief

bootcfg/http: Log errors for missing template metadata

---

examples/ignition/k8s-master.yaml

* Update to k8s 1.2.0 recommended admission-control settings
* Improves conformance test results (validate this and report in #71 )
* Upstream recommendation: http://kubernetes.io/docs/admin/admission-controllers/
* Related: https://github.com/coreos/coreos-kubernetes/issues/497
cc @aaronlevy

examples/k8s: Update apiserver admission-control

---

Documentation/ignition.md

More explicitly write about the difference between an Ignition template, and an Ignition config file.
This may be slightly more redundant but I think it should help clarify common questions about Ignition files being written in YAML and the connection between metadata coming from a Group definition and how that gets used with an Ignition template.

Documentation: More details about Ignition templating

---

contrib/dnsmasq/build-aci

On rkt v1.6,
```
sudo rkt run coreos.com/dnsmasq:v0.2.0 -- -d
sudo rkt run coreos.com/dnsmasq:v0.2.0                             # as a daemon
dnsmasq[5]: dnsmasq: failed to bind DHCP server socket: Permission denied
```
* Original issue https://github.com/coreos/rkt/issues/2706
* Original PR: https://github.com/coreos/coreos-baremetal/pull/218
We'll need to build, upload, and sign a coreos.com/dnsmasq:v0.3.0. The version isn't particularly significant, they just need to match some coreos-baremetal release since that's where coreos.com serves from and I'd rather not override v0.2.0.
@iaguis

Update dnsmasq ACI retained capabilities

---

Documentation/config.md
Makefile
contrib/systemd/bootcfg.service

* systemd users can use /etc/bootcfg.env if they choose to use environment files

*: Use agnostic Makefile, stop creating empty env file

---

examples/README.md
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml

* Example clusters can use a pre-configured DHCP server for network setup rather than provisioning hosts with a networkd config
fyi @brianredbeard

examples: Optionally skip networkd configuration

---

Documentation/bootkube.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/kubernetes.md
examples/groups/bootkube-install/install.json
examples/groups/etcd-install/install.json
examples/groups/k8s-install/install.json
examples/ignition/install-reboot.yaml
examples/ignition/install-shutdown.yaml
scripts/README.md
scripts/get-coreos

* Examples which install CoreOS to disk should reference a CoreOS install image from bootcfg assets to speed up installs and improve the offline use-case
* Update scripts/get-coreos to download and verify the CoreOS install image
Improves #226

examples: Use coreos-install baseurl

---

.gitignore
CHANGES.md
Documentation/config.md
Documentation/dev/develop.md
bootcfg/cli/root.go
bootcfg/client/client.go
bootcfg/rpc/grpc.go
bootcfg/tlsutil/info.go
bootcfg/tlsutil/tlsutil.go
cmd/bootcfg/main.go
examples/etc/bootcfg/.gitignore
examples/etc/bootcfg/README.md
examples/etc/bootcfg/cert-gen
examples/etc/bootcfg/openssl.conf

* Add gRPC client-to-server TLS transport security and server verification (prevent MITM)
* A CA certificate (e.g. ca.crt) should be used to sign a server certificate (server.crt for a private key server.key)
* gRPC API server requires a server certificate and key to be enabled (passed via -cert-file and -key-file)
* gRPC client bootcmd tool must verify the server identity using a known CA (passed to bootcmd via -ca-file)
* Example client and server commands/flags with rkt and Docker
* Require TLS client auth for gRPC API
* gRPC API server requires a CA certificate to authenticate clients (passed via -ca-file)
* gRPC clients must authenticate with a client certificate and key (passed via -cert-file and -key-file)
* Add examples/etc/bootcfg/cert-gen to create fake (ca, server, client) …

Require gRPC TLS transport security, server verification, client authentication

---

Documentation/bootkube.md
examples/ignition/bootkube-master.yaml
examples/ignition/bootkube-worker.yaml

* Users no longer need to scp a bootkube binary
* Disable auto-updates until kube-apiserver checkpointing is done
@aaronlevy

examples/bootkube: Use bootkube image and disable auto-updates

---

Documentation/bootkube.md
examples/README.md
examples/ignition/bootkube-master.yaml
examples/ignition/bootkube-worker.yaml

* Upgrade the self-hosted Kubernetes cluster example to use bootkube v0.1.1 which supports apiserver checkpointing in order to tolerate apiserver downtime (e.g. controller reboot)
* Bumps Kubernetes version to v1.3.0-beta.2
* Re-enable CoreOS auto-updates
cc @derekparker

examples/bootkube: Upgrade from bootkube v0.1 to v0.1.1

---

Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/kubernetes.md
examples/groups/k8s-docker/node1.json
examples/groups/k8s-docker/node2.json
examples/groups/k8s-docker/node3.json
examples/groups/k8s-install/node1.json
examples/groups/k8s-install/node2.json
examples/groups/k8s-install/node3.json
examples/groups/k8s/node1.json
examples/groups/k8s/node2.json
examples/groups/k8s/node3.json
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml

* examples/{k8s,k8s-install,k8s-docker}: Mount /etc/resolv.conf into kubelet
* Kubelet must be able to resolve DNS names which are known to the host. This fixes a bug in which only IP's could be used for `k8s_controller_endpoint` metadata
* Run etcd on the controller and proxies on the workers. This updates the `k8s`, `k8s-install`, and `k8s-docker` clusters to match the self-hosted Kuberntes setup (i.e. `bootkube`)
* Remove `fleet_metadata` for simplicity, it is not a requirement for Kubernetes
Updated clusters have been validated in local VMs and on physical hardware ala [dghubble/metal](https://github.com/dghubble/metal)

Fix Kubernetes v1.2.4 clusters (static manifest variant)

---

bootcfg/http/cloud.go
bootcfg/http/generic.go
bootcfg/http/grub.go
bootcfg/http/handlers.go
bootcfg/http/http.go
bootcfg/http/ignition.go
bootcfg/http/ipxe.go
bootcfg/http/metadata.go
bootcfg/http/pixiecore.go
bootcfg/http/pixiecore_test.go
bootcfg/http/server.go

Now that we've switched to Logrus (#254) we can make use of its structured fields.
* Add info logs for errors matching machine groups or resolving profiles, or supported templates
* Add debug logs with successful match info
Here are a few examples:
If a query does not match any group's selectors:
```
[44542.643080] bootcfg[5]: time="2016-07-12T17:04:14Z" level=info msg="No matching group" labels=map[mac:52:54:00:a1:9b:ad]
```
If the group typo's the name of the profile (should be `k8s-master` not `k8s-meister`):
```
[44637.346291] bootcfg[5]: time="2016-07-12T17:05:48Z" level=info msg="No profile named: k8s-meister" group=node1 group_name="k8s controller" labels=map[mac:52:54:00:a1:9c:ae]
```
If a config (ipxe, grub, Ignition, cloud-config, generic) referenced in a profile is missing:
``` …
```

bootcfg/http: Add structured info/debug logging

---

CHANGES.md
bootcfg/http/cloud.go
bootcfg/http/cloud_test.go
bootcfg/http/generic.go
bootcfg/http/generic_test.go
bootcfg/http/ignition.go
bootcfg/http/ignition_test.go
bootcfg/http/metadata.go
bootcfg/http/metadata_test.go
bootcfg/http/parse.go
examples/ignition/install-reboot.yaml
examples/ignition/install-shutdown.yaml

* Serve /metadata including group metadata, selectors, and query variables in KEY=value "env file" format lines
* Recurse into nested maps (e.g. OUTER_INNER=val)
Ordered after: #278 
Closes: #182 #84

Serve nested group metadata, selectors, and query vars as /metadata "env file"

---

CHANGES.md
bootcfg/http/cloud.go
bootcfg/http/cloud_test.go
bootcfg/http/generic.go
bootcfg/http/generic_test.go
bootcfg/http/ignition.go
bootcfg/http/ignition_test.go
bootcfg/http/metadata.go
bootcfg/http/metadata_test.go
bootcfg/http/parse.go
examples/ignition/install-reboot.yaml
examples/ignition/install-shutdown.yaml

* Add query parameters to template variables, referenced by `{{.request.query.param}}`
* Render Ignition/Fuze, cloud-config, and generic templates and metadata with collected variables
* Replace template variable {{.query}} with {{.request.raw_query}} (breaking)
rel. #182

bootcfg/http: Add request query values to template variables

---

Documentation/api.md
Documentation/bootcfg.md
Documentation/bootkube.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/kubernetes.md
Documentation/torus.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/etcd-install/install.json
examples/groups/k8s-install/install.json
examples/ignition/bootkube-master.yaml
examples/ignition/bootkube-worker.yaml
examples/profiles/bootkube-master.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd-proxy.json
examples/profiles/etcd.json
examples/profiles/grub.json
examples/profiles/install-reboot.json
examples/profiles/install-shutdown.json
examples/profiles/k8s-master-install.json
examples/profiles/k8s-master.json
examples/profiles/k8s-worker-install.json
examples/profiles/k8s-worker.json
examples/profiles/pxe-disk.json
examples/profiles/pxe.json
examples/profiles/torus.json
scripts/README.md
scripts/get-coreos

* Bump CoreOS Alpha from 1053.2.0 to 1109.1.0. Clusters which install to disk auto-update, so this bump just changes the "starting" version. Deployed alpha clusters should already be using 1109.1.0.
* Update self-hosted Kubernetes cluster example to use bootkube v0.1.2.
* Bump Kubernetes from v1.3.0-beta.2_coreos.0 to v1.3.0_coreos.1
cc @aaronlevy

examples: Update CoreOS version and bootkube

---

Documentation/deployment.md
Makefile
scripts/release-files

I've been playing with `bootcfg` on some ARM boards and other folks might like to do the same. Include it in the next release.
cc @crawford Makefile opinions?

Add ARM to release architectures

---

README.md
examples/README.md
examples/groups/rktnetes/node1.json
examples/groups/rktnetes/node2.json
examples/groups/rktnetes/node3.json
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml
examples/profiles/rktnetes-controller.json
examples/profiles/rktnetes-worker.json

* Add an example Kubernetes cluster with rkt as the container runtime, CoreOS 1122.0.0, and rkt 1.11.0 (i.e. rktnetes).
* Ports over the great work by rkt folks https://github.com/coreos/coreos-kubernetes/pull/551 and @pbx0 
Don't merge yet.
```
NAME                STATUS    AGE
node1.example.com   Ready     10m
node2.example.com   Ready     10m
node3.example.com   Ready     11m
```
All pods.
```
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE
kube-system   heapster-v1.1.0-3647315203-gcl2w            2/2       Running   0          11m
kube-system   kube-apiserver-node1.example.com            1/1       Running   0          12m
kube-system   kube-controller-manager-node1.example.com   1/1       Running   0          12m
kube-system …
```

examples: Add Kubernetes with rkt runtime (rktnetes)

---

CHANGES.md
Documentation/bootkube.md
examples/groups/bootkube-install/node1.json
examples/groups/bootkube/node1.json
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/profiles/bootkube-controller.json

* Use bootkube v0.1.4 for self-hosted bootstrapping

examples: Update self-hosted Kubernetes to v1.3.4

---

Documentation/bootkube.md
examples/groups/bootkube-install/node1.json
examples/groups/bootkube-install/node2.json
examples/groups/bootkube-install/node3.json
examples/groups/bootkube/node1.json
examples/groups/bootkube/node2.json
examples/groups/bootkube/node3.json
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml

This works with the [fork of bootkube](https://github.com/dghubble/bootkube), which supports DNS names (needed until Kubernetes 1.4).
* Self-hosted Kuberntes api-server comes up without a hostname override and detects the hostname it should use from `uname -n`
* kube-apiserver name must correspond to routable kubelet hostname-override
* Provision /etc/hostname with the FQDN so `uname -n` can be used by Kubernetes (until NODE_NAME is avail. in k8s 1.4)
rel: #261 #291 https://github.com/coreos/bootkube/issues/89 https://github.com/coreos/bootkube/pull/90
cc @sym3tri @aaronlevy

examples/bootkube: Use DNS names for self-hosted Kubernetes

---

CHANGES.md
examples/README.md
examples/groups/etcd3-install/install.json
examples/groups/etcd3-install/node1.json
examples/groups/etcd3-install/node2.json
examples/groups/etcd3-install/node3.json
examples/groups/etcd3-install/proxy.json
examples/ignition/etcd3-proxy.yaml
examples/ignition/etcd3.yaml

* Use notify service type so dependent services don't start immediately
* Add etcd3-install example cluster
* etcd3-install installs CoreOS to disk and sets up a 3-node etcd3 cluster
* Additional machines are setup as etcd3 proxies
cc @gyuho

Update and add to etcd3 example clusters

---

Documentation/ignition.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/format-disk.yaml
examples/ignition/k8s-master.yaml
examples/ignition/k8s-worker.yaml
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml
examples/ignition/torus.yaml

* Use the "root" filesystem from the Ignition universal base config (path /sysroot)
* No need for custom named filesystem anymore
* https://coreos.com/ignition/docs/latest/examples.html#create-files-on-the-root-filesystem
wip: Update other reference clusters to replace "rootfs" with "root".
cc : @crawford

examples: Use universal root filesystem

---

examples/README.md
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml
examples/profiles/rktnetes-controller.json
examples/profiles/rktnetes-worker.json

* Resolves several docker2aci bugs in rkt 1.11.0 https://github.com/coreos/rkt/pull/3026
* Install to disk (rktnetes-install) is not yet working https://github.com/coreos/bugs/issues/1541
* Docker v1.12 dockerd fails if given the daemon argument (doesn't break rktnetes, but fix is desirable)
* Applies https://github.com/coreos/coreos-kubernetes/pull/642
cc: @pbx0 @euank

Update rktnetes to 1151.0.0 and fix Docker 1.12 issue

---

scripts/get-coreos

Previously this matched very specific HTTP status codes only, while now it matches any success or redirection status code. It also works for "HTTP/2" answers in addition to "HTTP/2.0".
Fixes: #331

get-coreos: Be more relaxed about the channel-or-version-not-found check

---

Documentation/bootkube.md

In the bootkube documentation make the command to copy kubeconfig
files to all nodes copy-pastable by adding a for loop.

bootkube docs: make scp kubeconfig command copy-pastable

---

scripts/devnet

The QEMU/KVM tutorial/development setup asks users to run `bootcfg` and `dnsmasq` (DHCP/TFTP/DNS) on the virtual bridge where QEMU/KVM VMs will be created. This script adds an optional "fast-track" which sets this up, but does it with proper rkt run transient units.
Run PXE services and bootcfg set to configure machines into an `etcd` example cluster.
```
$ ./scripts/devnet create etcd
Starting bootcfg with examples/groups/etcd mounted
Running as unit dev-bootcfg.service.
Starting dnsmasq to provide DHCP/TFTP/DNS services
Running as unit dev-dnsmasq.service.
```
Check logs as usual for systemd.
```
journalctl -u dev-bootcfg
journalctl -u dev-dnsmasq
```
Create the QEMU/KVM VMs with tutorial/development (known) hardware attributes.
```
./scripts/libvirt create
```
Stop and garbage collect …

scripts: Add devnet script to setup PXE/bootcfg bridge

---

scripts/devnet

Before:
$ sudo ./scripts/devnet
./scripts/devnet: line 20: $1: unbound variable
After:
$ sudo ./scripts/devnet
USAGE: devnet <command>
Commands:
create	create bootcfg and PXE services on the bridge
destroy	destroy the services on the bridge

scripts/devnet: print usage if no arguments are provided

---

CHANGES.md
Documentation/bootkube.md
Documentation/rktnetes.md
Documentation/torus.md
examples/README.md
examples/ignition/k8s-controller.yaml
examples/ignition/k8s-worker.yaml
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml

* Use CNI for Kubernetes clusters
* Replace --network-plugin-dir with --cni-conf-dir
* Add DefaultStorageClass to admission-control list
* Bump to v1.4.0_coreos.2 Hyperkube
* Update kube-* addons for 1.4 and use YAML manifests

examples/{k8s,rktnetes}: Update Kubernetes to v1.4.0_coreos.2

---

Documentation/rktnetes.md
examples/README.md
examples/groups/rktnetes-install/install.json
examples/profiles/rktnetes-controller.json
examples/profiles/rktnetes-worker.json

* rkt v1.14.0 is needed for rktnetes
* Validated via QEMU/KVM PXE boot
* Validated on lab hardware https://github.com/dghubble/metal/commit/68ac004a2345d04f4577f818f5765b8a0487114c (actually CoreOS Alpha 1192.0.0)
closes #353

examples/rktnetes: Update to CoreOS Beta 1185.1.0

---

CHANGES.md
Documentation/bootkube.md
Documentation/kubernetes.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/rktnetes-install/install.json
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/profiles/bootkube-controller.json
examples/profiles/bootkube-worker.json

* Render with [dghubble/bootkube](https://github.com/dghubble/bootkube) fork which supports DNS
* Start with [bootkube](https://github.com/kubernetes-incubator/bootkube) v0.2.0 with rkt
* Update on-host hyperkube to v1.4.0_coreos.0
cc @aaronlevy

examples: Update self-hosted Kubernetes to v1.4.0

---

CHANGES.md
Documentation/bootkube.md
Documentation/kubernetes.md
Documentation/rktnetes.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/k8s-controller.yaml
examples/ignition/k8s-worker.yaml
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml

* Update to fix http://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2016-7075 https://github.com/kubernetes/kubernetes/issues/34517
* Upgrade static Kubernetes to v1.4.3
* Upgrade self-hosted Kubernetes to v1.4.3
* Upgrade rktnetes to v1.4.3
* Self-hosted Kubernetes [Upgrade Guide](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/bootkube-upgrades.md) for existing clusters
Closes #366

Upgrade Kubernetes clusters to v1.4.3

---

examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/k8s-controller.yaml
examples/ignition/k8s-worker.yaml
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml

* Use the Kubelet `--pod-manifest-path`, `--config` is deprecated in Kubernetes 1.4+
* Self-hosted Kubernetes clusters expect the Kubelet ACI and VERSION to be read from an environment file on disk

examples: Use Kubelet --pod-manifest-path and EnvironmentFile

---

examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/etcd-proxy.yaml
examples/ignition/etcd.yaml
examples/ignition/etcd3-proxy.yaml
examples/ignition/etcd3.yaml
examples/ignition/k8s-controller.yaml
examples/ignition/k8s-worker.yaml
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml

* locksmithd should use etcd to lock for reboots
* The default best-effort strategy uses the reboot strategy if etcd isn't running temporarily

examples/ignition: Set reboot strategy to etcd-lock

---

Documentation/deployment.md
Documentation/dev/release.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
contrib/k8s/bootcfg-deployment.yaml
contrib/systemd/bootcfg-on-coreos.service

Although v0.4.1 was just a docs/scripts fix release for Tectonic and arm64, let's be consistent and use v0.4.1 everywhere.
Fix bad link mentioned in #376 while at it.

Documentation: Update deployment docs to use v0.4.1

---

Documentation/bootcfg.md
Documentation/config.md
Documentation/dev/develop.md
Documentation/getting-started-rkt.md
Documentation/grub.md
Documentation/network-setup.md
Documentation/torus.md
contrib/dnsmasq/README.md
contrib/dnsmasq/metal0.conf
examples/etc/bootcfg/README.md
scripts/README.md
scripts/devnet
scripts/tls/k8s-certgen

* Change CIDR from 172.15.0.0/16, which isn't a reserved private range
* Use a smaller CIDR, /24 is sufficient
If you have an old `metal0` bridge (`brctl show`) you should re-create it. Stop and cleanup any running pods.
```
sudo ./scripts/devnet destroy
sudo rkt gc --grace-period=0
```
Remove the old virtual bridge.
```
sudo rm /etc/rkt/net.d/20-metal.conf
sudo ip link set metal0 down
sudo  brctl delbr metal0
```
Update any `/etc/hosts` entries from `172.15.0.*` to `172.18.0.*`.
Follow [getting-started-rkt](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/getting-started-rkt.md) to re-create metal0 on `172.18.0.0/16`. Copied here for ease.
```
sudo bash -c 'cat > /etc/rkt/net.d/20-metal.conf << EOF
{
"name": "metal0",
"type": "bridge",
"bridge": "metal0",
"isGateway": …
```

Documentation: Change metal0 bridge to 172.18.0.0/24

---

Documentation/deployment.md

Deployment document refers to `scripts/tls` for self-signed certificates.
The current location is actually `examples/etc/bootcfg`

Documentation: update deployment.md cert-gen references

---

contrib/systemd/bootcfg-for-tectonic.service
contrib/systemd/bootcfg-local.service

Update/fix the `bootcfg` systemd units.
* `bootcfg.service` - bundled in the official RPM
* `bootcfg-on-coreos.service` - for running bootcfg on CoreOS via rkt
* validated by using bootcfg to create a CoreOS cluster, then running bootcfg on a node
* `bootcfg-local.service` - for generic Linux users copying the binary
fyi @omkensey

contrib/systemd: Update bootcfg systemd units

---

examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/k8s-controller.yaml
examples/ignition/k8s-worker.yaml
examples/ignition/rktnetes-controller.yaml
examples/ignition/rktnetes-worker.yaml

* Save the rkt pod uuid on start and remove pod resources (files, network) on restart, without waiting on gc

examples: Remove old kubelet pods by uuid-file

---

CHANGES.md
Documentation/api.md
Documentation/bootcfg.md
Documentation/network-booting.md
Documentation/openpgp.md
bootcfg/http/pixiecore.go

* coreos-baremetal must support production Tectonic customers on bare-metal
* Focus on real-world, varied network environments and flexibility
* iPXE provides better hardware introspection than being limited to MAC
* Matching must extend beyond hardware identifiers
* ISC DHCP and dnsmasq provides production DHCP service
* If we desire all-in-one ease, it will be accomplished by packaging
* Drop Pixiecore (all-in-one binary) from the setups we can support or recommend
* Code remains so anyone who was using it isn't taken by surprise and there are no hard feelings :)

Documentation: Deprecate Pixiecore support

---

CHANGES.md
Documentation/bootkube.md
examples/groups/bootkube-install/node1.json
examples/groups/bootkube-install/node2.json
examples/groups/bootkube-install/node3.json
examples/groups/bootkube/node1.json
examples/groups/bootkube/node2.json
examples/groups/bootkube/node3.json
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml

* Update bootkube version to stop requiring the forked binary; bootkube now allows DNS names
* https://github.com/kubernetes-incubator/bootkube/pull/151
cc @aaronlevy

examples: Upgrade self-hosted Kubernetes to v1.5.1

---

scripts/libvirt

* virt-install created VMs which reboot themselves should actually reboot in order to mirror real machines
cc @ericchiang @rithujohn191 this should improve our lives

scripts: Add virt-install flag so reboots work

---

CHANGES.md
Documentation/bootkube.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml

* Self-hosted Kubernetes now runs flannel as a daemonset
This may require a return to the dghubble fork of bootkube for render, to remove the api-server advertise address, but ideally not.
cc @aaronlevy @pbx0

examples: Update Kubernetes to use self-hosted flannel

---

Documentation/getting-started-rkt.md
scripts/devnet

* Separate the stop and rm steps. Previously, users sometimes had to run devnet destroy a few times.
* Add devnet script to getting-started-rkt

scripts/devnet: Improve devnet script usability

---

Makefile

Unless `GOARM` is specified, the Go compiler will choose the compiling system's architecture as a target (similar to GCC's `-march=native`). This commit prevents that by explicitly selecting ARMv6 (e.g. Raspberry Pi 1) as the target.
According to the documentation, ARM64 does not need this, as ARMv8 is implicit and the value of `GOARM` is not considered for this architecture.
See-Also: https://github.com/golang/go/wiki/GoArm

Lock architecture to ARMv6 for linux-arm images

---

Documentation/api.md
Documentation/bootkube-upgrades.md
Documentation/bootkube.md
Documentation/cloud-config.md
Documentation/config.md
Documentation/deployment.md
Documentation/dev/develop.md
Documentation/dev/release.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/grub.md
Documentation/ignition.md
Documentation/kubernetes.md
Documentation/machine-lifecycle.md
Documentation/matchbox.md
Documentation/network-booting.md
Documentation/network-setup.md
Documentation/openpgp.md
Documentation/rktnetes.md
Documentation/troubleshooting.md

This fixes two issues, one is a problem the other is... less so.
1. (problem) Some codeblocks include syntax of the form `{{.foo.bar}}` which conflicts with the jekyll markdown parser. These needed to be escaped in with a `{{% raw %}}` block. This was only in three docs.
2. (less so) The codeblocks existed in two different (but technically valid) forms: `<indent>` and ` ```language ` gates. The latter is preferred among the CoreOS project docs, and is the only officially supported codeblock method I could find.

Docs: standardize codeblocks to ``` fencing

---

internal/smoke/etcd
internal/smoke/k8s
scripts/devnet
scripts/get-kubectl

This exposes some of the smoke testing bits to start doing this in the open.
* Smoke test etcd and k8s cluster bring-up
* Requires a suitable executor host (internal)

internal: Add smoke testing scripts

---

Documentation/api.md
Documentation/bootkube-upgrades.md
Documentation/bootkube.md
Documentation/cloud-config.md
Documentation/config.md
Documentation/deployment.md
Documentation/dev/develop.md
Documentation/dev/release.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/grub.md
Documentation/ignition.md
Documentation/machine-lifecycle.md
Documentation/matchbox.md
Documentation/network-booting.md
Documentation/network-setup.md
Documentation/openpgp.md
Documentation/rktnetes.md
Documentation/troubleshooting.md

Performed the following checks:
- sentence case
- index heading 2
- matchbox - proper noun and capitalize
files under Documentation have been modified.

Documentation/*.md: Make headings sentence case 

---

cmd/matchbox/main.go

* 1.8 changed the behavior of url.Parse so it is no longer appropriate for parsing values like 0.0.0.0:8080
* Pass the address directly to http.ListenAndServe which gives reasonable errors when bad values are used

cmd/matchbox: fix -address parsing when built with Go 1.8

---

Jenkinsfile
scripts/get-bootkube
scripts/get-kubectl
tests/smoke/bootkube
tests/smoke/etcd3
tests/smoke/k8s

* Smoke test against the checkout scm. This tests cluster configuration changes proposed on origin branches. It does not yet build a new matchbox to test proposed code changes at the same time.
* Increase the etcd3 timeout and trap EXITs to cleanup
* Simplify bootkube and kubectl binary curling

tests: Improve Jenkins smoke testing reliability

---

CHANGES.md
Documentation/bootkube.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
scripts/get-bootkube

* Upgrade to self-hosted Kubernetes v1.5.4
* Use bootkube v0.3.10
* Disable anonymous-auth flag for on-host kubelet
* Set the client CA for the on-host kubelet, based on the kubeconfig

examples: Update self-hosted Kubernetes to v1.5.4

---

scripts/get-bootkube
scripts/get-kubectl

* Cached bootkube binary causes smoke test failures when a new version is needed

scripts: Always download bootkube and kubectl

---

CHANGES.md
Documentation/bootkube.md
Documentation/kubernetes.md
Documentation/rktnetes.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/k8s-controller.yaml
examples/ignition/k8s-worker.yaml
scripts/get-bootkube
scripts/get-kubectl

* Bump kubectl version to v1.5.5
* Bump bootkube to v0.3.12
Smoke tests: https://jenkins-tectonic.prod.coreos.systems/job/matchbox/job/update-kubernetes/
cc @aaronlevy @ericchiang

examples: Update Kubernetes (static, self-hosted, rktnetes) to v1.5.5

---

CHANGES.md
Documentation/bootkube.md
Jenkinsfile
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
scripts/get-bootkube

* Bump bootkube to v0.3.13
* Use hyperkube v1.5.6_coreos.0

examples: Update self-hosted Kubernetes to v1.5.6

---

Documentation/deployment.md
README.md
contrib/k8s/matchbox-deployment.yaml
contrib/k8s/matchbox-ingress.yaml
contrib/k8s/matchbox-service.yaml

Demonstrate deploying a public matchbox behind Ingress and verify Terraform apply can update machine configs.
* Show matchbox deployment, service, and TLS secret creation
* Provide an Ingress resource for exposing HTTP and gRPC APIs
* Add note mentioning matchbox can be run publicly if best practices are followed
Note: 
* Guides for the different ways to correctly run Nginx Ingress Controllers on a bare-metal cluster is left for a future document.
* Tutorials on how to use the alpha Terraform plugin are left for a future document

contrib/k8s: Run matchbox on Kubernetes behind Ingress

---

CHANGES.md
Documentation/bootkube.md
Jenkinsfile
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
scripts/get-bootkube

* Render self-hosted assets with bootkube v0.4.0
* Relax bootkube smoke test Jenkins timeout

examples: Upgrade self-hosted Kubernetes to v1.6.1

---

Documentation/deployment.md
Makefile

* Stop shipping or mentioning the bootcmd CLI program. Reasons:
* bootcmd has never been built out into a user-facing CLI tool. Its a client example.
* terraform-provider-matchbox addresses the underlying need to add matchbox objects at runtime
* Keep bootcmd implementation to serve as an example of how to write a gRPC client to matchbox
Closes #153 #162

Makefile: Remove bootcmd from the release tarball

---

Documentation/getting-started-rkt.md
Documentation/grub.md
Documentation/network-setup.md
contrib/dnsmasq/CHANGES.md
contrib/dnsmasq/Makefile
scripts/devnet

* [quay.io/coreos/dnsmasq](https://quay.io/repository/coreos/dnsmasq) v0.4.0 is available
* dnsmasq package version 2.76
* Rebuilds with alpine:3.5 base image to receive patches
* Updates CoreOS `grub.efi` to be recent (stable, 1298.7.0)
* Update docs `coreos.com/dnsmasq` ACI references to `quay.io/coreos/dnsmasq`. Specify v0.4.0 when appropriate
* Update Jenkins CI to use the new dnsmasq:v0.4.0 image

Update docs, changelog, and scripts for dnsmasq:v0.4.0

---

examples/terraform/bootkube-install/bootkube.tf

* Terraform example typo's the port number in the etcd_endpoints
* Causes worker etcd-gateway to fail so Container Linux updates may not been coordinated by locksmith
Cluster create tests don't yet cover the terraform reference clusters.

examples/terraform: Fix bootkube worker etcd_endpoints port

---

examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/ignition/etcd3-gateway.yaml
examples/ignition/etcd3.yaml
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
examples/terraform/modules/profiles/cl/etcd3-gateway.yaml.tmpl
examples/terraform/modules/profiles/cl/etcd3.yaml.tmpl

* Update self-hosted Kubernetes node labels
* Update kubelet wrapper env variables and location
* Update etcd3 from 3.1.0 to 3.1.6

examples: Sync with bootkube and etcd3

---

Documentation/api.md
Documentation/bootkube.md
Documentation/deployment.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/kubernetes.md
Documentation/matchbox.md
Documentation/rktnetes.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/etcd3-install/install.json
examples/groups/k8s-install/install.json
examples/groups/rktnetes-install/install.json
examples/groups/simple-install/install.json
examples/profiles/bootkube-controller.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd3-gateway.json
examples/profiles/etcd3.json
examples/profiles/grub.json
examples/profiles/install-reboot.json
examples/profiles/install-shutdown.json
examples/profiles/k8s-controller.json
examples/profiles/k8s-worker.json
examples/profiles/simple-install.json
examples/profiles/simple.json
examples/terraform/bootkube-install/bootkube.tf
examples/terraform/etcd3-install/etcd3.tf
scripts/devnet
scripts/get-coreos

This cannot pass CI until the new version is added to the assets directory on the CI executor nodes.

Update Container Linux to 1298.7.0 and pin dev/test matchbox version

---

.gitignore
Documentation/getting-started.md
README.md
examples/README.md
examples/terraform/simple-install/cl/coreos-install.yaml.tmpl
examples/terraform/simple-install/cl/simple.yaml.tmpl
examples/terraform/simple-install/groups.tf
examples/terraform/simple-install/profiles.tf
examples/terraform/simple-install/provider.tf
examples/terraform/simple-install/terraform.tfvars.example
examples/terraform/simple-install/variables.tf

* Introduces matchbox alongside terraform as a first class client
* Targets the reader setting up physical machines on-premise, rather than QEMU/KVM development with rkt or docker
* Includes a new example which just installs Container Linux with an ssh key
* Most folks start learning about matchbox by bringing up a few Container Linux machines, not by provisioning a complete etcd or Kubernetes cluster. This intro tutorial embraces that so readers aren't overwhelmed. Provisioning multi-node clusters and understanding the many things that can be done with a Container Linux config comes next.
Closes #485

Documentation,examples: Add getting started tutorial with terraform

---

CHANGES.md
Documentation/deployment.md
Documentation/dev/release.md
Documentation/getting-started-rkt.md
contrib/k8s/matchbox-deployment.yaml
contrib/systemd/matchbox-for-tectonic.service
contrib/systemd/matchbox-on-coreos.service

Starting in v0.6.0, we will no longer be shipping ACIs for matchbox (or dnsmasq or other contrib images). Quay.io images can be used by rkt and docker just fine. ACI build scripts are kept only for local development purposes and may be removed at a future date. cc @philips

*: Prepare for v0.6.0 release

---

contrib/rpm/matchbox.spec

This is the RPM spec file used for Copr builds, updated for v0.6.0. It should be kept in the repo and imported by Copr.

contrib/rpm: Add matchbox RPM spec file

---

examples/ignition/k8s-controller.yaml

Reverts part of #470. We should revert to leaving the curl `--fail` off of PUTs and POSTs. When flannel or k8s-addons restart (e.g. system reboot), these scripts fail because the object already exists.
Fixes #490

examples/ignition: Remove --fail from curl PUT/POST's

---

CHANGES.md
Documentation/bootkube.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
scripts/get-bootkube
tests/smoke/bootkube

Updates both the regular and terraform based self-hosted Kubernetes clusters. Jenkins tests only PXE a 3-node bare-metal cluster using the non-terraform flow for now. Terraform testing is manual and I'll report back.

examples: Update self-hosted Kubernetes to v1.6.2

---

examples/terraform/bootkube-install/README.md

Previously, the terraform readme was incomplete by only including
terraform plan and apply commands. Additionally, the readme was
updated to include instructions for updating the profiles module
source.
Fixes #502

examples: updates terraform readme to include get

---

Documentation/bootkube.md
examples/ignition/bootkube-controller.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
scripts/get-bootkube

* Contains a few fixes to bootkube logging and checkpointing

examples: Update from bootkube v0.4.1 to v0.4.2

---

.gitignore
Documentation/bootkube.md
examples/terraform/.gitignore
examples/terraform/README.md
examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/bootkube.tf
examples/terraform/bootkube-install/provider.tf
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/bootkube-install/variables.tf
examples/terraform/etcd3-install/README.md
examples/terraform/etcd3-install/etcd3.tf
examples/terraform/etcd3-install/provider.tf
examples/terraform/etcd3-install/terraform.tfvars.example
examples/terraform/etcd3-install/variables.tf
examples/terraform/modules/profiles/cl/container-linux-install.yaml.tmpl
examples/terraform/modules/profiles/outputs.tf
examples/terraform/modules/profiles/profiles.tf
examples/terraform/modules/profiles/variables.tf

Rename and cleanup cluster profiles
* Add `container-linux-install` profile to install Container Linux (installs from public download site)
* Add `cached-container-linux-install` profile to install Container Linux from cached matchbox assets (previously called `coreos-install`)
Improve configurability of cluster examples:
* Add `matchbox_http_endpoint` and `matchbox_rpc_endpoint` as variables
* Remove dghubble ssh public key from default
* Add a terraform.tfvars.example and gitignore terraform.tfvars
Add etcd3 cluster tutorial and Terraform modules usage document (WIP)

Improve terraform examples, tutorials, and re-usable modules

---

scripts/libvirt

Create QEMU/KVM VMs with more disk or RAM than the defaults.
```
export VM_RAM=2048; export VM_DISK=12; sudo -E ./scripts/libvirt create
```

scripts/libvirt: Allow QEMU/KVM disk size to be customized

---

.gitignore
contrib/rpm/matchbox.spec

Fixing the source URL format to confirm to more normative rpmbuild
standards and to allow for proper use of spectool/rpmspectool.  This
change now produces a proper archive with the name and version number
used.

contrib/rpm: Fixing the source URL format

---

examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/bootkube.tf
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/bootkube-install/variables.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl

* Add an option to try experimental self-hosted etcd which uses the etcd-operator to deploy an etcd cluster as pods atop Kubernetes and disables the on-host etcd cluster on controllers and gateway on workers
* When enabled, configure locksmithd to coordinate reboots through self-hosted etcd since there is no on-host etcd to use.
Warning: This feature is still experimental and potentially [dangerous](https://github.com/coreos/tectonic-installer/pull/601#issuecomment-300242512). It is opt-in.

examples/terraform: Add experimental self-hosted etcd option

---

Jenkinsfile
scripts/devnet
tests/smoke/etcd3-terraform
tests/smoke/etcd3.tfvars

* Test PXE booting the Terraform-based etcd3 cluster in parallel with other clusters
This requires a few additions to executors (bc its the first terraform-based example):
* Install terraform v0.9+
* Add a .terraformrc file which points to a `terraform-provider-matchbox` binary
* Add the matchbox fake/testing TLS certs in ~/.matchbox
rel #508

Jenkinsfile,tests: Add etcd3-terraform cluster to pipeline

---

CHANGES.md
examples/ignition/bootkube-controller.yaml
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl

I noticed a difference btw these examples and bootkube examples is that bootkube disables workload scheduling on controllers as of Kubernetes v1.6. Let's do the same.
*Note: This means clusters must have at least 1 controller and 1 worker to be useful.*

examples: Add NoSchedule taint to bootkube controllers

---

README.md
examples/README.md
examples/terraform/modules/README.md

Highlight new terraform-based examples more prominently rather than burying them under the `examples/terraform` subfolder.

Organize README examples listing and links

---

examples/terraform/bootkube-install/cluster.tf
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/bootkube-install/variables.tf
examples/terraform/etcd3-install/etcd3.tf
examples/terraform/etcd3-install/terraform.tfvars.example
examples/terraform/etcd3-install/variables.tf
examples/terraform/modules/bootkube/groups.tf
examples/terraform/modules/bootkube/variables.tf
examples/terraform/modules/profiles/cl/container-linux-install.yaml.tmpl
scripts/get-coreos

Currently, when using `terraform`, the setup is using a generic image which can cause issues on some platforms. Common problem is the lack of `VM Guest Tools`, when installing on a VMware platform.
This PR adds the ability to fetch OEM images with `get-coreos` and allows a user to specify an oem image in `terraform.tfvars`.

Add support for OEM images

---

Documentation/bootkube.md
examples/ignition/bootkube-controller.yaml
examples/terraform/bootkube-install/variables.tf
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/bootkube/variables.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
scripts/get-bootkube

* Update bootkube cluster example to use bootkube v0.4.3 for render and start
* Update terraform-based bootkube-install cluster example to use v0.4.3 for start and terraform ([assets](https://github.com/dghubble/bootkube-terraform/pull/1))

examples: Update Kubernetes to use bootkube v0.4.3

---

Jenkinsfile
tests/smoke/bootkube-terraform
tests/smoke/bootkube.tfvars

Matchbox origin branches now test PXE booting and provisioning the following clusters on each commit:
* 3-node etcd
* 3-node etcd (terraform based)
* 3-node static Kubernetes
* 3-node self-hosted Kubernetes
* 3-node self-hosted Kubernetes (terraform-based, upstream for Tectonic)

tests: Add cluster tests for bootkube-install (terraform-based)

---

examples/terraform/bootkube-install/variables.tf
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/bootkube/groups.tf
examples/terraform/modules/bootkube/variables.tf

Use the Terraform `cidrhost` interpolation, based on the same trick in use in https://github.com/coreos/tectonic-installer/pull/767.
This removes the ability to input the service IP's, but these were not truly customizable anyway. `bootkube start` (bootstrapping) has assumptions about the offset for each service component (kube-apiserver, kube-dns, self-hosted etcd, bootstrap self-hosted etcd). The correct values will be calculated on the user's behalf.

Calculate Kubernetes service IPs based on the service CIDR

---

CHANGES.md
Documentation/bootkube.md
README.md
examples/README.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
scripts/get-bootkube
tests/smoke/bootkube-terraform
tests/smoke/etcd3-terraform

* Update bootkube example cluster to v1.6.4
* Update bootkube (terraform-based) cluster to v1.6.4
* Update bootkube Terraform module to v1.6.4
* Uses bootkube v0.4.4 https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.4.4
cc @aaronlevy @diegs

Update Kubernetes from v1.6.2 to v1.6.4

---

Jenkinsfile
scripts/test
tests/smoke/bootkube
tests/smoke/bootkube-terraform

The bootkube-terraform test leaves behind terraform PIDs which run apply and interfere with terraform-based tests. This leaves the fleet of executors in a bad state. Temporarily disable these tests and roll the executors.
Closes #541 #523

tests: Temporarily disable bootkube (terraform-based) cluster testing

---

.travis.yml
glide.lock
glide.yaml
vendor/golang.org/x/crypto/openpgp/keys.go
vendor/golang.org/x/crypto/openpgp/packet/packet.go
vendor/golang.org/x/crypto/openpgp/packet/private_key.go
vendor/golang.org/x/crypto/openpgp/packet/public_key.go
vendor/golang.org/x/crypto/openpgp/packet/public_key_v3.go
vendor/golang.org/x/crypto/openpgp/packet/signature.go
vendor/golang.org/x/crypto/openpgp/read.go
vendor/golang.org/x/crypto/openpgp/s2k/s2k.go
vendor/golang.org/x/crypto/openpgp/write.go

Shouldn't really affect us, but let's bump to the new Go version and update vendored openpgp since it hasn't been updated in a while and uses `elliptic.P256()`

Update openpgp package and bump Go to 1.8.3

---

CHANGES.md
Documentation/deployment.md
Documentation/getting-started.md
scripts/devnet

* Release will allow docs team to update docs (also closes https://github.com/coreos/tectonic-installer/issues/672)
* Release branch will be used to avoid deprecation changes being included in the point release
* Bumping Go to 1.8.3 for release images and binaries (#552)
* I'm not planning an RPM release. Docs and Go build version are independent from RPM releases so there are effectively no changes to the package.
* Clarifies #550 
Branch to be tagged:
https://github.com/coreos/matchbox/tree/release-v0.6.1

CHANGES.md: Prepare for a v0.6.1 docs point release

---

examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/cluster.tf
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/bootkube-install/variables.tf
examples/terraform/etcd3-install/README.md
examples/terraform/etcd3-install/etcd3.tf
examples/terraform/etcd3-install/terraform.tfvars.example
examples/terraform/etcd3-install/variables.tf
examples/terraform/modules/bootkube/groups.tf
examples/terraform/modules/bootkube/profiles.tf
examples/terraform/modules/bootkube/variables.tf
examples/terraform/modules/profiles/cl/container-linux-install.yaml.tmpl
examples/terraform/modules/profiles/profiles.tf
examples/terraform/modules/profiles/variables.tf
tests/smoke/bootkube.tfvars

Features in the re-usable modules:
These same features need to make their way into Tectonic as well.
rel #545 #549

Add some minor Terraform variables

---

Documentation/deployment.md

Copy matchbox-local.service to /etc/systemd/system/matchbox.service
rather than bare dir.

Doc/deployment.md: Cp local config to correct location

---

Documentation/bootkube.md
examples/groups/bootkube-install/node1.json
examples/groups/bootkube-install/node2.json
examples/groups/bootkube-install/node3.json
examples/groups/bootkube/node1.json
examples/groups/bootkube/node2.json
examples/groups/bootkube/node3.json
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/bootkube/groups.tf
examples/terraform/modules/bootkube/ssh.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
tests/smoke/bootkube

Matchbox Kubernetes cluster examples/modules now enable on-host etcd TLS always - there is not option to turn it off. Kubernetes clusters can now **finally!** be deployed in networks alongside untrusted servers. etcd TLS for experimental self-hosted etcd is tracked in #262.
* Require etcd3 cluster peers to use TLS to secure communication channels and require clients to be authenticated with a TLS client certificate
* kube-apiserver (including bootstrap) communicates with TLS authenticated on-host etcd cluster
* Configure locksmith to speak directly to an etcd nodes. Stop running an etcd gateway on workers.
Checked
* Tested (manual) bootkube example
* Tested (manual) bootkube-install example to ensure locksmithd coordinates auto-updates
* Tested (terraform) bootkube-install example
cc …

examples: Use Kubernetes on-host etcd TLS

---

examples/terraform/modules/bootkube/outputs.tf

Enables module users to use the cluster's kubeconfig in their own, add-on infrastructure declarations, such as adding diskless workers.

examples/terraform/modules: Add outputs.tf with kubeconfig

---

Dockerfile

Clair scan picks up some zlib vulnerabilties. Not directly impacting, but alpine:3.6 has been out for a few weeks now.

Dockerfile: Update base image from alpine:3.5 to alpine:3.6

---

Documentation/deployment.md
contrib/k8s/matchbox-ingress.yaml

* Fixes Ingress controller issue upgrading from nginx-ingress-controller 0.9-beta.3 to 0.9-beta.4 through 0.9-beta.7
Closes #575

contrib/k8s: Use two Ingress resources for HTTP and TLS gRPC

---

Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
contrib/dnsmasq/docker0.conf
scripts/devnet

* Add create, status, and destroy subcommands that use docker as the container runtime for testing local QEMU/KVM clusters. Previously the script only worked using rkt as the local container runtime.
* Update getting started tutorials accordingly

scripts: Improve devnet script to allow using rkt or docker

---

Documentation/deployment.md

gRPC API verification step has invalid paths to client.crt and client.key; these are created in ~/matchbox-v0.6.1-linux-amd64/scripts/tls (depending on where the matchbox installer is extracted).

Correct path to client.crt and client.key

---

CHANGES.md
Documentation/bootkube.md
README.md
examples/README.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
scripts/dev/get-bootkube
scripts/dev/get-kubectl

* Upgrade to Kubernetes v1.6.6 and bootkube v0.4.5
* Enable TLS for experimental self-hosted etcd (on-host etcd TLS was added last time)
* Upstream manifest generation changes modify the flannel Daemonset, switch several control plane components to run as non-root, and add an explicit UpdateStrategy to the control plane components
Notes:
With this update, all Kubernetes clusters defined in the Matchbox project use etcd TLS.
Requires:

examples: Upgrade Kubernetes to v1.6.6

---

examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl

* Fixes a regression introduced in 6f02107 which upgraded to Kubernetes v1.6.6 and added self-hosted etcd with TLS
* Both on-host and self-hosted etcd now require clients to use TLS client certs so locksmithd
Closes #590

examples: Use etcd client certs in locksmithd dropin

---

scripts/devnet

Otherwise the gRPC server is not accessible.

scripts/devnet: open port 8081 when using docker

---

examples/ignition/install-reboot.yaml
examples/terraform/modules/profiles/cl/container-linux-install.yaml.tmpl
examples/terraform/simple-install/cl/coreos-install.yaml.tmpl

`After=network-online.target` *should* mean this isn't needed in most
cases, but per
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/, the
definition of "network-online" is a little shaky.
Regardless, being a little more resilient to network flakes and races is
a good thing. The count of `10` was arbitrarily chosen.
No particular testing done.

examples: include 'curl' retries

---

Documentation/getting-started.md

I made a small fix to pluralize "templates" where it was previously written:
> [...] to different profiles and template in machine-specific values.
Additionally, I added syntax highlighting for the code example that follows.

Documentation tweaks

---

Documentation/bootkube.md
Jenkinsfile
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml

* Update non-terraform Kubernetes cluster to use [bootkube v0.5.0](https://github.com/kubernetes-incubator/bootkube/releases). Fix changes to etcd TLS generation.
* Increase Jenkinsfile timeouts to account for slow Quay downloads in the test environment, being addressed in #601
Similar to https://github.com/kubernetes-incubator/bootkube/pull/621

Update non-terraform Kubernetes to use bootkube v0.5.0

---

examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/bootkube/ssh.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl

* [Render changes](https://github.com/dghubble/bootkube-terraform/pull/5) corresponding to bootkube v0.5.0
* Manually tested cluster bootstrapping, with/without self-hosted etcd, and locksmithd updating the master and recovery. Looks good. Jenkins cluster tests may or may not pass, see #601 
Last part to #602

examples: Update terraform Kubernetes to use bootkube v0.5.0

---

scripts/dev/get-bootkube

Requires bootkube to upload the v0.5.0 tarball
https://github.com/kubernetes-incubator/bootkube/issues/649

scripts/dev: Update bootkube render binary for tests

---

CHANGES.md
Documentation/bootkube.md
Documentation/cluster-addons.md
examples/addons/cluo/update-agent.yaml
examples/addons/cluo/update-operator.yaml
examples/groups/bootkube-install/node1.json
examples/groups/bootkube-install/node2.json
examples/groups/bootkube-install/node3.json
examples/groups/bootkube/node1.json
examples/groups/bootkube/node2.json
examples/groups/bootkube/node3.json
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/bootkube/groups.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl

* Use Container Linux Update Operator to coordinate reboots in Kubernetes clusters. Mask locksmithd.
* Switch Kubernetes (non-terraform) and Kubernetes (terraform) to use CLUO
* Add a docs page about cluster addons to be used by both flows
* Terraform modules `bootkube` and `profiles` (Kubernetes) now disable locksmithd. Those using the modules directly should take action to deploy CLUO (change).
Closes #487 and  https://github.com/dghubble/bootkube-terraform/pull/4

Switch Kubernetes clusters from locksmith to Container Linux Update Operator

---

tests/smoke/bootkube

* Introduced in ce3154cae962e868faa2b247d856e004eb8545a7
* Masked by larger-scale timeouts / issues in the testing env
Related to #601

tests/smoke: Fix etcd certs distribution in bootkube test

---

CHANGES.md
Documentation/bootkube.md
README.md
examples/README.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
scripts/dev/get-bootkube
scripts/dev/get-kubectl

* Updates Kubernetes clusters to v1.6.7 (terraform-based and non, on-host etcd and self-hosted etcd)
* Update to bootkube v0.5.1
* Updated bootkube-terraform module for bootkube v0.5.1: https://github.com/dghubble/bootkube-terraform/pull/6

examples: Update Kubernetes from v1.6.6 to v1.6.7

---

Documentation/api.md
Documentation/bootkube.md
Documentation/deployment.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/matchbox.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/etcd3-install/install.json
examples/groups/simple-install/install.json
examples/profiles/bootkube-controller.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd3-gateway.json
examples/profiles/etcd3.json
examples/profiles/grub.json
examples/profiles/install-reboot.json
examples/profiles/simple-install.json
examples/profiles/simple.json
examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/multi-controller.tfvars.example
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/etcd3-install/etcd3.tf
scripts/devnet
scripts/get-coreos
tests/smoke/bootkube.tfvars

* PXE boot and/or install using Container Linux at stable 1409.7.0 by default. We bump this every so often just to stay relatively current.

examples: Install clusters at Container Linux 1409.7.0 (stable)

---

CHANGES.md
Documentation/bootkube.md
README.md
examples/README.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
scripts/dev/get-bootkube
scripts/dev/get-kubectl

Update Kubernetes cluster examples and Terraform modules for v1.7.1. Use or target bootkube v0.6.0 asset generation:
* `bootkube render` (https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.6.0)
* bootkube-terraform module - https://github.com/dghubble/bootkube-terraform/pull/7

examples: Update Kubernetes to v1.7.1

---

contrib/dnsmasq/Dockerfile
contrib/dnsmasq/Makefile

* Update from alpine:3.5 to alpine:3.6
* List ports 67 and 69 so ACI conversion still works
Related to #620

contrib/dnsmasq: Bump dnsmasq image to v0.4.1

---

matchbox/server/server_test.go

Two error variables were being swallowed unhandled in the tests for the server package.

Fix swallowed errors in server package tests

---

Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
examples/terraform/etcd3-install/README.md

etcd examples set ETCDCTL_API=3 but are using v2 etcdctl commands. This
works on CL by accident because it ships with 2.3 so etcdctl doesn't
recognize the API env var.

Documentation: remove ETCDCTL_API=3 settings

---

matchbox/client/client.go
matchbox/client/client_test.go

* Provide better errors to clients that forget to specify the port or include a protocol scheme by mistake
* grpc-go uses net.SplitHostPort to validate server listener addresses are 'host:port' but doesn't validate Dial targets. https://github.com/grpc/grpc-go/blob/e81b5698fd6a1fdbae0c62f52e9aabdeee231b99/clientconn.go#L304
* Validating our clients provide a host:port is a simple sanity check / pass filter, it is by no means complete. Properly validating a client target depends on the resolver, see https://github.com/grpc/grpc-go/issues/1346.
Before, in a client like `terraform-provider-matchbox`, invalid endpoints produced:
```
failed to create Matchbox client or connect to https://matchbox.example.com:8081: context deadline exceeded
```
Its not very helpful if you don't know the format …

matchbox/client: Validate client endpoint is a host:port

---

scripts/get-coreos

The `version.txt` file is used by coreos-install if the version number is `current`.

Add version.txt download on get-coreos

---

CHANGES.md
Documentation/bootkube.md
README.md
examples/README.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/modules/bootkube/bootkube.tf
examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl
examples/terraform/modules/profiles/cl/bootkube-worker.yaml.tmpl
scripts/dev/get-bootkube
scripts/dev/get-kubectl

Update Kubernetes cluster examples (terraform-based and non) for Kubernetes v1.7.3.
~CI requires the bootkube binary be published: https://github.com/kubernetes-incubator/bootkube/issues/690~

examples: Update Kubernetes from v1.7.1 to v1.7.3

---

Documentation/grub.md
scripts/libvirt

In virt-install v1.4.2, the meaning of  `--pxe` changed from "allow pxe boot" to "always pxe boot." This breaks matchbox, since we expect hosts to pxe-boot only with empty hds. On hosts with v1.4.2, the VMs loop, re-installing CL over and over.
The flag isn't necessary anyways, since we pass `--boot=hd,network`, which enables pxe-booting.
[This](https://github.com/virt-manager/virt-manager/commit/ff3b4dc5b0b21393dbccc0f5f691b17bf1a761bd) is the offending virt-manager commit.

libvirt: don't pass --pxe

---

matchbox/client/client.go

Exposes the Select endpoint in matchbox/client just as the other
endpoints like Profiles, Ignition and Generic.
I might have missed if there is a reason for this not to be exposed, but I wanted the ability to lookup a profile based on e.g. a MAC-address (like the /grub HTTP API does).

matchbox/client: Expose Select endpoint

---

CHANGES.md
Documentation/bootkube.md
README.md
examples/README.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/cluster.tf
examples/terraform/modules/README.md
scripts/dev/get-bootkube
scripts/dev/get-kubectl
scripts/libvirt

* Update from bootkube v0.6.2 to v0.7.0 ([release](https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.7.0))
* Update kube-dns to fix dnsmasq vulnerability
* Update minimum required RAM from 1G to 1.5G

examples: Update Kubernetes from v1.7.5 to v1.7.7

---

CHANGES.md
Documentation/bootkube.md
README.md
examples/README.md
examples/ignition/bootkube-controller.yaml
examples/ignition/bootkube-worker.yaml
examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/cluster.tf
scripts/dev/get-bootkube

* Switch to the `gcr.io/google_containers/hyperkube:v1.8.2`
* Fixes a memory leak in the kube-apiserver v1.8.1
Relevant:
* https://github.com/kubernetes-incubator/bootkube/pull/750
* https://github.com/poseidon/typhoon/commit/60bc8957c924f45d898cff55a2a647ac21f11790

Update to Kubernetes v1.8.2

---

Documentation/api.md
Documentation/bootkube.md
Documentation/deployment.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/matchbox.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/etcd3-install/install.json
examples/groups/simple-install/install.json
examples/profiles/bootkube-controller.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd3-gateway.json
examples/profiles/etcd3.json
examples/profiles/grub.json
examples/profiles/install-reboot.json
examples/profiles/simple-install.json
examples/profiles/simple.json
examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/cluster.tf
examples/terraform/bootkube-install/multi-controller.tfvars.example
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/etcd3-install/etcd3.tf
scripts/devnet
scripts/get-coreos
scripts/libvirt
tests/smoke/bootkube.tfvars

* Increase minimum RAM required to use PXE image
* https://coreos.com/releases/#1520.5.0

examples: Bump Container Linux to stable 1520.8.0

---

.travis.yml

Travis CI is supposed to auto-publish images from master with the SHA tag to compliment official releases. In #647, the build and deploy matrix stopped matching so publishing stopped. This should fix.

travis.yml: Fix travis to publish master images

---

.travis.yml
CHANGES.md

* Build binaries for Docker images with Go 1.8.5
* Travis hasn't been publishing quay.io images since #647
* Travis should "deploy" publish the quay image for Go 1.8.5
rel #647 #671

travis.yml: Ensure deploy condition matches build matrix

---

Documentation/network-setup.md
contrib/dnsmasq/Makefile
contrib/dnsmasq/README.md
contrib/dnsmasq/docker0.conf
contrib/dnsmasq/get-tftp-files
contrib/dnsmasq/metal0.conf
examples/profiles/bootkube-controller.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd3-gateway.json
examples/profiles/etcd3.json
examples/profiles/install-reboot.json
examples/profiles/simple-install.json
examples/profiles/simple.json
examples/terraform/bootkube-install/cluster.tf
examples/terraform/modules/profiles/profiles.tf
examples/terraform/simple-install/profiles.tf
scripts/devnet
scripts/libvirt

* Add ipxe.efi to dnsmasq image's`/var/lib/tftpboot` directory
* Build `quay.io/coreos/dnsmasq:v0.5.0` Docker image
* Add initrd kernel argument respected only by UEFI https://github.com/coreos/bugs/issues/1239
* Improve network-setup docs and scripts to cover UEFI clients and to support launching UEFI QEMU/KVM clusters locally
* Ensure `./libvirt create-uefi` is usable with cluster examples
* Reduce references to grub.efi flow, its not a happy path
rel: https://github.com/coreos/bugs/issues/1239

contrib/dnsmasq: Add ipxe.efi for dnsmasq:v0.5.0

---

matchbox/http/ipxe.go
matchbox/http/ipxe_test.go

iPXE loads multiple initrds when each is given to it's own initrd command

fix loading multiple initrds

---

scripts/devnet

* Local examples scripts run Matchbox to generate Ignition v2.1.0 spec configs

scripts/devnet: Bump matchbox image version

---

Documentation/api.md
Documentation/bootkube.md
Documentation/deployment.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/matchbox.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/etcd3-install/install.json
examples/groups/simple-install/install.json
examples/profiles/bootkube-controller.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd3-gateway.json
examples/profiles/etcd3.json
examples/profiles/grub.json
examples/profiles/install-reboot.json
examples/profiles/simple-install.json
examples/profiles/simple.json
examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/multi-controller.tfvars.example
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/etcd3-install/etcd3.tf
scripts/devnet
scripts/get-coreos
tests/smoke/bootkube.tfvars

* Use Docker 17.09 by default in Kubernetes clusters

examples: Update Container Linux to stable 1576.4.0

---

CHANGES.md
Documentation/deployment.md
Documentation/dev/release.md
Documentation/getting-started-rkt.md
contrib/k8s/matchbox-deployment.yaml
contrib/systemd/matchbox-for-tectonic.service
contrib/systemd/matchbox-on-coreos.service
scripts/devnet

Holiday Release
* Add gRPC API endpoints for managing generic (experimental) templates
* Update Container Linux config transpiler to v0.5.0
* Update Ignition to v0.19.0, render v2.1.0 Ignition configs
* Drop support for Container Linux versions below 1465.0.0 (breaking)
* Build Matchbox with Go 1.8.5 for images and binaries
* Remove Profile `Cmdline` map (deprecated in v0.5.0), use `Args` slice instead
* Remove pixiecore support (deprecated in v0.5.0)
* Remove `ContextHandler`, `ContextHandlerFunc`, and `NewHandler` from the `matchbox/http` package.
* Upgrade Kubernetes example clusters to v1.8.4
* Kubernetes examples clusters enable etcd TLS
* Deploy the Container Linux Update Operator (CLUO) to coordinate reboots of Container Linux nodes in Kubernetes clusters. See the cluster [addon …

*: Update Matchbox version to v0.7.0

---

scripts/tls/cert-gen

Ensure an `index.txt.attr` file exists, it gets cleaned up at the beginning of the script.
Closes #690

scripts/tls: Fix cert-gen to add index.txt.attr

---

.travis.yml

this also fixes the golint url to use the new location, to fix ci.

travis: update to latest supported go major versions

---

scripts/get-flatcar

Similar to `get-coreos`, add a helper script `get-flatcar` to download
Flatcar assets.
Follow up for https://github.com/poseidon/typhoon/pull/315

scripts: add helper script `get-flatcar`

---

CHANGES.md
Documentation/api.md
Documentation/bootkube.md
Documentation/deployment.md
Documentation/getting-started-docker.md
Documentation/getting-started-rkt.md
Documentation/matchbox.md
README.md
examples/README.md
examples/groups/bootkube-install/install.json
examples/groups/etcd3-install/install.json
examples/groups/simple-install/install.json
examples/profiles/bootkube-controller.json
examples/profiles/bootkube-worker.json
examples/profiles/etcd3-gateway.json
examples/profiles/etcd3.json
examples/profiles/grub.json
examples/profiles/install-reboot.json
examples/profiles/simple-install.json
examples/profiles/simple.json
examples/terraform/bootkube-install/README.md
examples/terraform/bootkube-install/cluster.tf
examples/terraform/bootkube-install/multi-controller.tfvars.example
examples/terraform/bootkube-install/terraform.tfvars.example
examples/terraform/etcd3-install/etcd3.tf
scripts/devnet
scripts/get-coreos
tests/smoke/bootkube.tfvars

Update Container Linux from 1576.5.0 to 1911.4.0 since newer ignition configs may be in use (depending on terraform-provider-ct version)

Update Kubernetes (terraform) example to v1.12.3

---

.travis.yml

* Test changes on Travis using the current Go v1.11.x release
* Push container images built with Go v1.11.5

Update Go version from v1.11.1 to v1.11.5

---

Documentation/config.md
Documentation/deployment.md
Documentation/dev/release.md
Documentation/getting-started-docker.md
Documentation/getting-started.md
Documentation/matchbox.md
README.md
contrib/k8s/matchbox-deployment.yaml
contrib/systemd/matchbox-for-tectonic.service
contrib/systemd/matchbox-on-coreos.service
examples/terraform/bootkube-install/README.md
examples/terraform/etcd3-install/README.md
examples/terraform/modules/README.md
scripts/devnet

* Bump versions of terraform provider plugins to current
* Verify getting started with docker and etcd example

Update links to Matchbox, Quay, and terraform provider plugins

---

.travis.yml
CHANGES.md

* Document that release binaries and the container image binary will be built with Go v1.11.7

Build binaries with Go v1.11.7

---

.travis.yml
contrib/dnsmasq/Dockerfile
contrib/dnsmasq/Makefile
contrib/dnsmasq/travis-deploy

* Automatically publish dnsmasq image on merge to a branch named "dnsmasq". Similar to how matchbox is automatically published from master. Set the version based on git SHA
* Update base image from alpine:3.6 to alpine:3.9 to address #712
* https://docs.travis-ci.com/user/deployment/script/#passing-arguments-to-the-script (most similar)
Followups:
Need push access and if everything is working, `dnsmasq` branch should probably be protected.

Update coreos/dnsmasq image and automate deploys

---

CHANGES.md
Documentation/deployment.md
Documentation/dev/release.md

Matchbox releases will be signed by my GPG key, like other projects in the poseidon org. New docs:
Verify the release has been signed by Dalton Hubble's [GPG Key 8F515AD1602065C8](https://keyserver.ubuntu.com/pks/lookup?search=0x8F515AD1602065C8&op=vindex).
```sh
$ gpg --keyserver keyserver.ubuntu.com --recv-key 8F515AD1602065C8
$ gpg --verify matchbox-$VERSION-linux-amd64.tar.gz.asc matchbox-$VERSION-linux-amd64.tar.gz
gpg: Good signature from "Dalton Hubble <dghubble@gmail.com>"
```

Update Matchbox release signing process

---

CHANGES.md
Documentation/deployment.md
Documentation/dev/release.md
contrib/k8s/matchbox-deployment.yaml
contrib/systemd/matchbox-for-tectonic.service
contrib/systemd/matchbox-on-coreos.service
scripts/devnet

* Release Matchbox v0.8.0 before bumping big dependencies or components in future
* Establish the new Matchbox release process now that its managed under poseidon

Prepare for Matchbox v0.8.0 release

---

Documentation/deployment.md
Documentation/dev/release.md

Extend the long-form OpenPGP key to be the full fingerprint (hex characters added to the left, the right remains the same). I've also signed this commit.

Show the full OpenPGP fingerprint instead of long form

---

Documentation/bootkube.md
Documentation/deployment.md
Documentation/getting-started-docker.md
Documentation/getting-started.md
Documentation/grub.md
Documentation/machine-lifecycle.md
Documentation/matchbox.md
Documentation/network-setup.md
Documentation/troubleshooting.md
contrib/dnsmasq/README.md
scripts/devnet

* Use the quay.io/poseidon/dnsmasq image, which receives periodic updates. The coreos/dnsmasq image is outdated
Related: https://github.com/poseidon/matchbox/issues/712

Stop referencing outdated coreos/dnsmasq image

---

scripts/get-fedora-coreos

* Download kernel, initramfs, and raw image needed for cached installs of Fedora CoreOS

Add get-fedora-coreos script to download files

---

CHANGES.md
Documentation/config.md
Documentation/deployment.md
Documentation/dev/develop.md
Documentation/dev/release.md
Documentation/getting-started.md
Documentation/grub.md
Documentation/matchbox.md
Documentation/network-setup.md
README.md
contrib/dnsmasq/README.md
scripts/README.md
scripts/devnet
scripts/libvirt

* rkt achieved its mission creating the OCI standard, pluggable runtimes, and prevented Docker world domination. We can now proceed with disarmament
* Few, if any, developers still use rkt locally

Remove rkt tutorials, docs, and scripts

---

.travis.yml
CHANGES.md

* Build matchbox with Go v1.12.10
* Add go v1.13.x to the test matrix
* Drop Go v1.10.x from the test matrix

Update Go versions for build and test matrix

---

.travis.yml
CHANGES.md

* Use Go version v1.13.4 in Travis image builds and for building release binaries

Update Go version from v1.12.10 to v1.13.4

---

docs/deployment.md
docs/getting-started.md
examples/README.md
examples/terraform/etcd3-install/README.md
examples/terraform/modules/README.md
scripts/dev/release-files
scripts/tls/README.md

* Docs were moved to `docs` in https://github.com/poseidon/matchbox/pull/769

Fix links to Documentation to new docs directory

---

.travis.yml
CHANGES.md
Makefile

* Travis creates a Go v1.13.4 environment, checks out the source repo, and _then_ executes the `install` block to install `golint`
* With module-aware Go, this means installing `golint` caused a diff, before the Matchbox `make` target was invoked. Builds were correctly identified as "dirty" as a result
* Release tags v0.8.1 and v0.8.2 have been removed to avoid any confusion. Container images with binaries considered dirty have been removed as well. These tags and images only existed for a few minutes, the problem was flagged during the release process.
* Details: https://github.com/poseidon/matchbox/pull/773#issuecomment-557846875

Disable Go modules while installing golint tool on Travis

---

CHANGES.md
go.mod

* `go` modifies `go.mod` during the build to add `go 1.13`, which causes the build to be considered dirty (Travis: https://travis-ci.org/poseidon/matchbox/jobs/616382705)

Set `go 1.13` in go.mod to avoid a diff at build

---

Dockerfile
Makefile
contrib/dnsmasq/Dockerfile
contrib/dnsmasq/Makefile

* Add `make image` and `make push` targets to use rootless buildah for regular development. Retain docker build for Travis CI

Update base container image from alpine:3.10 to alpine:3.11

---

scripts/dev/release-files

The docs suggest it is (https://matchbox.psdn.io/deployment/#kubernetes) but they aren't there. They're only in the git checkout. Which is fine, but for consistency.

`contrib/k8s` not in the release images

---

docs/network-setup.md

* Either link to the Quay.io image or directly to the source code contrib folder
* Close https://github.com/poseidon/matchbox/issues/789

Fix contrib/dnsmasq links

---

contrib/k8s/matchbox-deployment.yaml
contrib/k8s/matchbox-ingress.yaml

Two minor fixes to allow Kubernetes deployments to work:
* Move the deploy to the app/v1 api version ([removed from Kubernetes 1.16 onward](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) - the app/v1 has been supported since Kubernetes 1.9)
* Modify the RPC ingress name so that is does not conflict with the primary matchbox ingress.

Fix for Kubernetes

---

examples/terraform/simple-install/groups.tf

With terraform v0.12.13, this gives the following errors
```
Error: Unsupported block type
on groups.tf line 18, in resource "matchbox_group" "node1":
18:   selector {
Blocks of type "selector" are not expected here. Did you mean to define
argument "selector"? If so, use the equals sign to assign it a value.
```

Fix simple-install to work with terraform 12

---

contrib/dnsmasq/get-tftp-files

* Remove grub.efi from `quay.io/poseidon/dnsmasq` container image. Container Linux images are EOL and have been removed

Fix dnsmasq container image build

---

docs/index.md
requirements.txt

* Update mkdocs-material from v6.0.2 to v6.1.0

Fix indentation in docs/index.md tutorials

---

.dockerignore

* Avoid dockerignore'ing source files, since this means a `COPY . /src` and git status (e.g. make) will detect the commit state as dirty/deletions

Fix dirty version in recent container images

---

CHANGES.md

* Multi-arch (and single-arch) images are published to `quay.io/poseidon/matchbox`

Mention multi-arch container images in CHANGES

---

docs/getting-started-docker.md
examples/ignition/fedora-coreos.ign
examples/profiles/fedora-coreos-install.json
examples/profiles/fedora-coreos.json
scripts/get-fedora-coreos
scripts/libvirt

* Update Fedora CoreOS live PXE and disk install examples to Fedora 33
* Increase libvirt VM memory from 2GB to 3GB to support live PXE example, which is mostly just for laptop examples/demos.
Reduce the VM count from 3 to 2 to compensate.
* Change `fedora-coreos.ign` to suggest using an ed25519 SSH key since Fedora CoreOS 33 disables RSA SHA1 (256 is still ok
but most people won't know which they have)

Update Fedora CoreOS examples for 33.20210117.3.2

---

.github/workflows/test.yaml

* Update Github Workflow `checkout` and `setup-go` actions
* Change `go get <tool>` to `go install <tool>`
* Remove Go v1.16

Add Go v1.18 to public Github Workflow

---

docs/deployment.md
docs/getting-started-docker.md
docs/getting-started.md
examples/README.md
examples/profiles/fedora-coreos-install.json
examples/profiles/fedora-coreos.json
examples/terraform/fedora-coreos-install/profiles.tf
examples/terraform/fedora-coreos-install/terraform.tfvars.example
examples/terraform/fedora-coreos-install/variables.tf
scripts/README.md
scripts/get-fedora-coreos

See individual commits for details.

Update Fedora CoreOS images and configuration

---

examples/terraform/fedora-coreos-install/profiles.tf

This PR updates the examples to match the FCOS iPXE [docs](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_ipxe). Without these changes, the server will fail to boot with this error:
```
/dev/root can't open blockdev
```

Update iPXE example to match the FCOS iPXE documentation

---

docs/deployment.md
docs/getting-started-docker.md
docs/getting-started.md
examples/ignition/fedora-coreos.ign
examples/ignition/fedora-coreos.yaml
examples/profiles/fedora-coreos-install.json
examples/profiles/fedora-coreos.json
examples/terraform/fedora-coreos-install/fcc/fedora-coreos.yaml
examples/terraform/fedora-coreos-install/profiles.tf
examples/terraform/fedora-coreos-install/provider.tf
scripts/README.md
scripts/libvirt
scripts/tls/cert-gen

* Add initrd=main karg directive for UEFI (ignored by BIOS)
* Update Butane config version to v1.4.0 (generates Ignition v3.3.0) in `fedora-coreos` and `fedora-coreos-install` examples
* Update virt-install flag --os-variant
* Removed virt-install deprecated flag --os-type
* Remove virt-install QEMU/KVM event preserve since it apparently wasn't implemented anyway and QEMU/KVM now warns about it
* Remove serial consol kernel argument from examples, but still mention it in docs
Rel:
* https://github.com/coreos/fedora-coreos-docs/pull/282
* https://www.spinics.net/linux/fedora/libvir/msg222078.html

Add initrd=main karg to examples and update QEMU/KVM setup

---

.github/workflows/test.yaml

* Default branch was renamed from master to main
* Internal build and publishing workflows were unaffected, the GitHub Action is just for public contribution vetting

Fix GitHub Actions unit tests workflow

---

docs/deployment.md
docs/getting-started-docker.md
examples/README.md
examples/groups/flatcar-install/flatcar.json
examples/groups/flatcar-install/install.json
examples/ignition/flatcar-install.ign
examples/ignition/flatcar-install.yaml
examples/ignition/flatcar.ign
examples/ignition/flatcar.yaml
examples/profiles/flatcar-install.json
examples/profiles/flatcar.json
examples/terraform/fedora-coreos-install/profiles.tf
examples/terraform/fedora-coreos-install/provider.tf
examples/terraform/flatcar-install/butane/flatcar-install.yaml
examples/terraform/flatcar-install/butane/flatcar.yaml
examples/terraform/flatcar-install/groups.tf
examples/terraform/flatcar-install/profiles.tf
examples/terraform/flatcar-install/provider.tf
scripts/README.md

* Flatcar Linux OS now supports Ignition v2.13+ which means it can accept Ignition v3.x spec's, like Fedora CoreOS. Matchbox supports this by serving Ignition documents directly
*Discontinue using Matchbox's Container Linux Config features in favor of its Ignition features
* Users of the poseidon/matchbox Terraform provider can pass a `matchbox_profile` `raw_ignition` contents with the desired Ignition v3.3 spec
* Users of the poseidon/ct Terraform provider can write Butane Config YAML, perform templating, and render an Ignition document using either the fcos or the flatcar variant
Rel: https://github.com/poseidon/terraform-provider-ct/releases/tag/v0.11.0

Update Flatcar Linux examples and use Ignition

---

scripts/get-flatcar

gpg key hosted at www.flatcar.org now

gpg key hosted at www.flatcar.org now

---

docs/deployment.md
docs/getting-started-docker.md
docs/getting-started.md
examples/profiles/fedora-coreos-install.json
examples/profiles/fedora-coreos.json
examples/terraform/fedora-coreos-install/terraform.tfvars.example
examples/terraform/fedora-coreos-install/variables.tf
scripts/README.md
scripts/get-fedora-coreos

* Pick up some recent bug fixes with root disks in QEMU setups

Update Fedora CoreOS examples to stable 36.20220906.3.2

---

go.mod
go.sum
matchbox/cli/generic_create.go
matchbox/cli/group_create.go
matchbox/cli/ignition_create.go
matchbox/cli/profile_create.go
matchbox/http/ipxe.go
matchbox/http/metadata_test.go
matchbox/http/render_test.go
matchbox/http/test_fixtures.go
matchbox/sign/writer_test.go
matchbox/storage/filestore_test.go
matchbox/storage/fs.go
matchbox/storage/fs_test.go
matchbox/tlsutil/tlsutil.go

* Replace ioutil methods with equivalent io and os methods
* Remove unneccesary types from slice literals
* Update the minimum Go version to v1.18

Fix notable Go standard library warnings and deprecations

---

go.mod
go.sum

* gopkg.in/yaml.v2 2.2.8 has a minor CVE thats still being indirectly used through one of our dependencies (https://github.com/coreos/go-semver)
* Force MVS to use v2.4.0 instead

Pin gopkg.in/yaml.v2 to v2.4.0

---

Dockerfile

* Allow automation tools to find the repo source, changelogs, and other release information via container image labels

Add opencontainer container image labels

---

CHANGES.md
Makefile
contrib/k8s/deployment.yaml
docs/deployment.md
docs/dev/release.md

* Emphasize that Container Linux Configs have been dropped and that Butane is the way forward to use modern Ignition v2
* Include some links to Flatcar Linux docs

Prepare release notes for v0.10.0 release

---

CHANGES.md
docs/ignition.md
examples/README.md
examples/ignition/fedora-coreos.yaml
examples/ignition/flatcar-install.yaml
examples/ignition/flatcar.yaml
examples/terraform/fedora-coreos-install/fcc/fedora-coreos.yaml
examples/terraform/flatcar-install/butane/flatcar-install.yaml
examples/terraform/flatcar-install/butane/flatcar.yaml
matchbox/http/ignition.go
matchbox/http/ignition_test.go

* Add support for fcos v1.5.0 Butane Configs
* Add support for flatcar v1.1.0 Butane Configs
* Render Butane or raw Ignition to Ignition spec v3.4.0 using Ignition's forward compatibility support
Rel:
* https://coreos.github.io/butane/config-fcos-v1_5/
* https://coreos.github.io/butane/config-flatcar-v1_1/
* https://coreos.github.io/ignition/configuration-v3_4/

Render Butane or raw Ignition to Ignition spec v3.4.0

---

CHANGES.md
examples/ignition/fedora-coreos.ign
examples/ignition/flatcar-install.ign
examples/ignition/flatcar.ign
examples/profiles/fedora-coreos-install.json

* Regenerate example Ignition using fcct v0.18.0 to produce Ignition spec v3.4.0 as a followup to https://github.com/poseidon/matchbox/pull/1079
* Fix one profile example where a double escape isn't needed

Update raw Ignition examples to use Ignition spec v3.4.0

---

.github/workflows/build.yaml
.github/workflows/test.yaml
Makefile
README.md

* Migrate from the internal Drone server using a GitHub Workflow to perform the multi-arch container image build
* Use self-hosted GitHub runners on ARM64 to perform the ARM64 build step faster that QEMU/KVM emulation
* Mandate approval for all workflow runs from outside contributors since the builds use push credentials and partially run internally

Migrate container image builds to GitHub Workflows

---

matchbox/http/ipxe.go

Some commands were added in the ipxeBootstrap to enable architecture detection based on the architecture the iPXE version used was built for. 
This is done through the use of an additional flag in the ipxeBootstrap string using the buildarch parameter.

CPU architecture detection with iPXE

---

.github/deploybot.yaml

* We now use GitHub Actions instead of a private Drone which is great for OSS build transparency, but one drawback to that change is that we no longer auto-deploy matchbox to internal Poseidon Labs infra
* We don't want public workflows for deploys to our private infra

Remove auto-deploys to Poseidon internal infra

---

cmd/matchbox/flakgutil.go
cmd/matchbox/main.go
go.mod
go.sum

* Remove dependency on github.com/coreos/pkg because the module is no longer maintained and it doesn't follow the usual release conventions
* The last time flagutils was touched as 9 years ago by me. Bring the function into the matchbox repo

Remove dependency on github.com/coreos/pkg

---

.github/workflows/mkdocs-pages.yaml
.github/workflows/summary.yaml
.github/workflows/wait-for-status-checks.yaml

* Add wait-for-status-checks reusable GitHub Workflow to wait for all status checks in a PR. Mark this as a required check so that GitHub auto-merge can be used
Rel: https://github.com/poseidon/wait-for-status-checks/

Add enforce workflow to wait for PR status checks

---

docs/api-http.md
docs/cloud-config.md
docs/machine-lifecycle.md
docs/matchbox.md

Fleet no longer seems to be used, and the docs link is broken.

Remove fleet references from docs

---

scripts/get-fedora-coreos
scripts/get-flatcar

I was using the get-flatcar script and I noticed a failure as a result of some changes in the layout of the assets. I updated the scripts to fail if they encounter a server error.

Fix asset fetching scripts and complain earlier in case of failure
